### ISSUE TITLE
Make Speakers block auto-complete etc.

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#107]
Make speakers block auto-complete Speakers as they are added in the admin.  Make it work like this image so added speakers can be drag-dropped to re-order:
![image](https://user-images.githubusercontent.com/463160/58775719-25d77300-85f1-11e9-8562-228c67621ac4.png)

Also have the block store the IDs of the Speakers and not the names so that it is not vulnerable to name changes.

**Comment by andycochran** [comment]
Tried to dig into this a bit, but I'm not sure how to use the ACF block builder.

**Comment by cjyabraham** [comment]
Yes, probably.  I don't like that idea.  It would mean having ACF just for that.

**Comment by cjyabraham** [comment]
I showed @meganelizabethphillips a workaround for this (having the searchable list of speakers open in a different tab) and she said she'd check with the team whether this would be adequate for now.

**Comment by rodmeurer** [comment]
It's done @cjyabraham 

https://github.com/LF-Engineering/lfevents/pull/409

![Captura de tela de 2020-01-10 11-00-44](https://user-images.githubusercontent.com/54405402/72158664-86097100-3399-11ea-9b1a-4b82e3e089c0.png)

**Comment by cjyabraham** [comment]
Very nice.  I'll deploy in the next few days.  It'll break existing blocks but I think there are only two on the live site so I'll replace them during the deploy.

**Comment by cjyabraham** [comment]
Tested, merged and ready to deploy.
