### ISSUE TITLE
Allow for adding an Event in the future when the current year's Event hasn't yet passed

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#168]
This will allow us to publish a splash page and newsletter signup more than a year in advance of an Event.

**Comment by cjyabraham** [comment]
another couple of options as discussed with @meganelizabethphillips and @andycochran :
3. Create a `/[event]-2020-coming-soon` page. Once 2019 is archived, redirect `/[event]-2020-coming-soon` to `/[event]`. When 2020 is archived, the coming-soon url won't matter.
4. Have a section of the 2019 site that advertises sponsorship information for the 2020 Event.

@dankohn can we get your opinion on this?  It is already an issue for the 2020 Kubecon NA so we need a solution now.

**Comment by cjyabraham** [comment]
If option 4 is sufficient, it is the easiest to execute and manage.  We could have a topnav menu item and subpages dedicated to all info for the 2020 Event. 

However, I'm guessing in certain cases you'll want the whole event to be built out while the current year is still not passed?  In which case, I like option 3.

**Comment by dankohn** [comment]
I prefer 3, please. When we archive the site in the future, we could also change the coming-soon to redirect directly to the archive rather than triggering two redirects.

**Comment by cjyabraham** [comment]
Correction: WP doesn't do a good job of this slug redirection when you've already redirected the target slug.  Reopening.

**Comment by andycochran** [comment]
Yay! 3 was my idea. 😎

We should be clear in the instruction/training about how creating 301s willy-nilly is permanent/risky. Whoever will be setting up these redirects, I don't want them to be sert up to fail. Need to make sure they're very aware of how these work.
