### ISSUE TITLE
Design pattern for multi-part pages

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#179]
Design and implement a solution for the following types of multi-part pages:
- [Co-located events](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/co-located-events/)
- [CFP page with left menu](https://events.linuxfoundation.org/events/servicemeshcon-2019/program/call-for-proposals-cfp/)
- [CFP using accordions](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/cfp/)
- [Weird tabbing example](https://events.linuxfoundation.org/events/open-fintech-forum-2019/program/cfp/)

One key requirement is we need to be able to link to a part of the page and have that link be discoverable.  One idea is to do something similar to how github does it when you hover over a header on the [readme](https://github.com/LF-Engineering/lfevents).

**Comment by andycochran** [comment]
Looks like this is a content problem. 

![image](https://user-images.githubusercontent.com/409279/65393814-c47c1100-dd53-11e9-918e-62dcc1879c6b.png)

![image](https://user-images.githubusercontent.com/409279/65393817-d1990000-dd53-11e9-80fa-6ab033ac4183.png)

The non-breaking spaces on each side of the link force it to be on the same line as the words before and after it, which makes that line go wider than the window.

**Comment by andycochran** [comment]
Same issue here: 

![image](https://user-images.githubusercontent.com/409279/65393839-4c621b00-dd54-11e9-91e8-f42641356164.png)

**Comment by cjyabraham** [comment]
So are you saying it's a content problem?  Do you recommend any action or should we just ignore?

**Comment by andycochran** [comment]
IDK where the `nbsp;` were coming from. But I was able to edit the content to nix the horizontal scrolling. Everywhere there was a long link, I simply deleted the space to each side of it and added a new space. With a quick search, I didn't find any reason why WP would be automatically adding `nbsp;` to the content. But this isn't a problem with the code. Closing.
