### ISSUE TITLE
Create some kind of style guide to help Megan and editors

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#198]
I think mainly they need to know what size of image they should use for particular blocks, for logos, etc.  For some instances we can provide this info in the block admin UI itself.  Elsewhere we could add to the bottom of [Admin Instructions](https://docs.google.com/document/d/1mvIuw-R9k_gbnZn_iV04qNTjG33u_lXwFlN7s-lgJ1Y/edit)?

**Comment by cjyabraham** [comment]
I've started [the section in the Admin Instructions](https://docs.google.com/document/d/1mvIuw-R9k_gbnZn_iV04qNTjG33u_lXwFlN7s-lgJ1Y/edit#heading=h.eoadtlfn2fih).  The values I put in there are just pulled from the [current kubecon site](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/) so feel free to verify and edit.

**Comment by andycochran** [comment]
@cjyabraham @meganelizabethphillips I've updated the section of the admin instructions on image sizes. Sizing images is… kinda complicated. So let's talk through these specs on our next training call.
