### ISSUE TITLE
Minify JavaScript and CSS

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#208]
Best practice for modern websites is to concatenate and minify each of the JavaScript and CSS into a single file and name them based on the hash of the content. That JS and CSS can then be served with an infinite cache lifetime and any change to JS or CSS produces a new file that is immediately fetched.

Rails [guides](https://guides.rubyonrails.org/asset_pipeline.html#main-features) has a good explanation of how this works. Note that Rails includes the additional functionality of replacing all image filenames with the hash so that images can be cached forever and never need to be reloaded unless they're evicted from the cache or the image changes.

I have not found a Wordpress plugin that implements this full functionality.

I think we can go live without this but I would love to find a solution that is reliable and measure whether the extra delay of using a plugin in development is worth it for having faster pages in production. Options:

Hummingbird is probably the best known optimizer.
https://premium.wpmudev.org/project/wp-hummingbird/

Other Minify options
https://wordpress.org/plugins/search/minify/

This one seems very popular, and the developer is available for additional work if we wanted it
https://wordpress.org/plugins/fast-velocity-minify/

**Comment by cjyabraham** [comment]
We are currently running with just 5 js files and 5 css files.  They are all minified.  I don't think there's much to gain by concatenating them so I'll close for now.

I feel our current speeds don't require further performance work.  The biggest things to watch for as we build out Event sites will be image use (see #279) and pages that get to be too long with too much content.
