### ISSUE TITLE
Install an image compression plugin

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#209]
Lighthouse in Google Chrome Inspector is giving a 71 on https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/ partially because of the overly large JPEGs. Should we consider using an image compression plugin to avoid large pictures getting accidentally uploaded?

https://wordpress.org/plugins/search/optimize+images/

Should we try Smush Pro and Hummingbird Pro at $49 a month?
https://premium.wpmudev.org/projects/category/plugins/

**Comment by thetwopct** [comment]
Just FYI, WordPress 5.3 release will introduce new filters to make sure large images are not loaded by users. It won't give as much control as Imsanity, so probably still worth keeping it 
https://make.wordpress.org/core/2019/10/09/introducing-handling-of-big-images-in-wordpress-5-3/

**Comment by cjyabraham** [comment]
Thanks for the heads up.  I'll try and remove Imsanity if possible #313
