### ISSUE TITLE
Upgrade Foundation to fix history accumulation in multi-part pages

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#223]
When the next version of Foundation is released, upgrade it so that multi-part pages doesn't accumulate browser history.

**Comment by cjyabraham** [comment]
@andycochran Which version of Foundation are we waiting for for this fix?

**Comment by andycochran** [comment]
The fix is in the development branch. So any further release should contain this fix. 

I can look into the possibility of patching this one particular file.

**Comment by andycochran** [comment]
Here is the PR that addresses this issue: https://github.com/foundation/foundation-sites/pull/10833

**Comment by cjyabraham** [comment]
@andycochran has there been any indication as to when there will be a new release?  Can you evaluate the feasibility of patching this now instead of waiting for the full release?
