### ISSUE TITLE
CVent rewrite: Scope out registration requirements

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#254]
Create a thorough Product Requirement Document that includes screenshots of every user-facing and every admin-facing screen in Cvent as well as all reporting that the LF makes use of. Also include a list of missing features, and whether any are necessary prior to switchover.

Evaluate possible Salesforce (SFDC) implementations including Lightning and those listed on https://github.com/MinnPost/object-sync-for-salesforce#finding-other-sync-options.

**Comment by cjyabraham** [comment]
@dankohn since the cvent rewrite will be managed by someone else, do you still want me to do this or can we close the issue?
