### ISSUE TITLE
Use H1 tags for Event pages

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#258]
From @thetwopct review.  I think having an H1 improves SEO.

**Comment by andycochran** [comment]
I can't find where we're not using `h1` tags. Please clarify. 

![image](https://user-images.githubusercontent.com/409279/65393891-107b8580-dd55-11e9-8c73-8b608dcede5e.png)

![image](https://user-images.githubusercontent.com/409279/65393915-5d5f5c00-dd55-11e9-81d1-95d3c845039b.png)

**Comment by cjyabraham** [comment]
Could we add one to the [Event parent page](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/)? Maybe we could wrap the logo in an h1?

**Comment by andycochran** [comment]
I've added `<h1 class="show-for-sr"><?php the_title(); ?></h1>` to the event parent page, which should help with SEO, but not wreck the custom layouts.
