### ISSUE TITLE
Max limit to width of site

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#259]
from @thetwopct review: On a full screen iMac, some of the elements go too wide. Perhaps consider max-width 1600px or 1800px on container/elements.

**Comment by andycochran** [comment]
The content does have a max width unless we specifically set the Gutenberg block to full-width. Are there examples of places we'd like to improve max widths?

**Comment by thetwopct** [comment]
Just looking at the events page, the menu, speakers and sponsors logo sections
![lfeventsci (20190923)](https://user-images.githubusercontent.com/10615884/65400382-73702980-ddf4-11e9-851a-70602d2e6e54.jpg)
 look like they need it. Seems the UGB plugin overrides what is there. Should do it:

```
.speakers-section .speaker-list, .wp-block-cgb-sponsors-block {
max-width: 1200px;
margin-left: auto;
margin-right: auto;
}
```
The menu needs a bit more doing to it, there's a lot going on. Maybe it kinda works being edge to edge.

Screenshot dump attached for ref

**Comment by andycochran** [comment]
Ah. I see what you mean. I've not look at this enough on a extremely large monitors. I'll experiment with putting better `max-width` on the whole site.
