### ISSUE TITLE
Consider hiding blocks that we don't use

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#260]
from @thetwopct :
I normally find users get a bit confused with the Gutenberg block adder in WP Admin. So typically I would only show allowed blocks that have been styled for use. Using allowed_block_types.
Also some can be done here - disable Stackable Blocks not being used
https://dev-lfeventsci.pantheonsite.io/wp/wp-admin/admin.php?page=stackable

**Comment by cjyabraham** [comment]
We'll wait for @meganelizabethphillips to find her fav blocks and then make a decision together on which to possibly hide.

**Comment by meganelizabethphillips** [comment]
@cjyabraham I'd like to avoid this if possible - I feel limited with the tools already and don't want to limit any further.

**Comment by cjyabraham** [comment]
I discussed again with @meganelizabethphillips and she'd like to keep all blocks available.  I'll close this issue for now.
