### ISSUE TITLE
Create LFEvents-Bot

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#269]
Create a GitHub account called LFEvents-Bot and have it post the Pantheon staging server to issues instead of having @cjyabraham do so. See https://github.com/cncf/landscape/commits?author=CNCF-Bot

**Comment by cjyabraham** [comment]
My sense is that I need a unique email to setup this account, then add it to the repo.  Is there an email we could create for this?  Or should I just use the CNCF-Bot?

**Comment by taylorwaggoner** [comment]
@cjyabraham, I created eventsbot@cncf.io for this.  Thanks!

**Comment by cjyabraham** [comment]
Thanks @taylorwaggoner .

[Bot is functional](https://github.com/LF-Engineering/lfevents/pull/271).

**Comment by dankohn** [comment]
Not done yet! Please pick a robot's image for the account. I suggest https://images-na.ssl-images-amazon.com/images/I/41h5C9nRU9L.jpg

**Comment by cjyabraham** [comment]
[Now we're talking!](https://github.com/LF-Engineering/lfevents/pull/271)
