### ISSUE TITLE
Open community events in new tab and have external link icon

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#274]

**Comment by andycochran** [comment]
4ef89f0f6e16f9f6bdb3f643c50b1e70237ab0db addresses this issue. 

It does the following: 
- Adds external link icon to the Community Events links on the homepage and opens them in a new tab 
- Adds external link icon to the Community Events on /about/community-events/ 

However, I edited the temporary files in the `search-filter/` directory that are specific to content IDs. This seems… wrong. Why are we using content IDs in the theme? If we move these icons to `results.php`, we'll need a condition to check if the page uses the default template or the Community Events template.

**Comment by andycochran** [comment]
Reassigned. @cjyabraham, please review this and either adjust the code or close.

**Comment by cjyabraham** [comment]
The external link icons look a bit bold and stronger than the title font.  Do you think you could mute it a bit, the same way you did for the external link icons on the topnav?

Good idea on the search-filter templates: #277
