### ISSUE TITLE
Full-width blocks on about page

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#275]
Megan is trying to make full-width color blocks on the [sponsors page](https://live-lfeventsci.pantheonsite.io/about/sponsor/) but can't since there is some style constraining them.  First, are we sure we want to allow full-width blocks on that page?  I'm not sure it will look good.  Second, if we want to allow them, please make the change.

**Comment by andycochran** [comment]
I agree that there shouldn't need to be full-width blocks on the about pages. They should appear very uniform/consistent. 

The template has a container which limits the width of all content; adding full-width blocks would be a rather large change. 

IDK if the desire for full-width is to simply replicate the existing site. But I'd like to better understand the desire/goal here, and make a suggestion for an alternative way to solve the problem.

**Comment by cjyabraham** [comment]
Agreed.  Closing.
