### ISSUE TITLE
Can you improve the mobile view of the Calendar search form

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#276]
Maybe move the drop-downs and button closer together?
<img width="312" alt="Screen Shot 2019-09-28 at 3 28 27 PM" src="https://user-images.githubusercontent.com/463160/65813871-ef0f1380-e204-11e9-8351-5268a4c4c6e4.png">

**Comment by andycochran** [comment]
Closed by e6f379bc78cc26c103598f24d4be337b5bd6083f — which also prevents some FOUC where the `<select>` shows before the plugin/JS loads.

**Comment by cjyabraham** [comment]
Nice!
