### ISSUE TITLE
Figure out if deployments are busting browser cache effectively

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#278]

**Comment by thetwopct** [comment]
I would normally build an additional step in to Gulp builds, so it deletes the build folder, recreates and updates with touch so file modification times are always up to date. 

https://www.npmjs.com/package/del
https://www.npmjs.com/package/gulp-touch-cmd

.pipe(touch());

**Comment by cjyabraham** [comment]
they seem to be working fine right now... will keep an eye on this.
