### ISSUE TITLE
Project-specific landing pages to promote KubeCon San Diego

### ISSUE THREAD

**Issue by lindsayshaw** [LF-Engineering/lfevents#281]
Hello all, 

- This issue is to create 4 KCCNCNA19 web pages following this design/content template: https://events.linuxfoundation.org/prometheus-kubecon-eu-2018/ 

- Each page is for one project. The 4 projects we need pages for are Kubernetes, Envoy, Prometheus, and Helm. 
- The page url should be nested inside the events site, but are not in navigable from the menu, these are standalone landing pages, structure like https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2018/prometheus-kubecon-eu-2018/ NOT like https://events.linuxfoundation.org/prometheus-kubecon-eu-2018/

There are 5 sections to each page
1. Hero image with community talk photo, event logo on the left, project logo in the center, date and location on the right
2. Call to action slice, "Join the <Project> Community at KubeCon + CloudNativeCon, call to action button that says "Register Now" directing to https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/register/ 
3. Don't miss <Project> talks, pulling in 6 of the project's talks from the KCCNCNA schedule
4. A section that pulls in the project's description and embed's a project video from previous event + Register Now button
5. 2 pictures from previous event that has the project logo 

Note, @dankohn would like this to a be a top priority this week.

**Comment by KimMcMahon** [comment]
Moving this to the WordPress issue board:
https://github.com/cncf/wordpress-site/issues/110
