### ISSUE TITLE
Make tab container blocks full width in edit screen

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#287]

**Comment by andycochran** [comment]
Making these full width and getting rid of the blue background. Put a light gray dashed around them so you can see where the blocks are. Could remove that too if it's unnecessary, but I think it's helpful when writing the content to see where the blocks start/stop.

![image](https://user-images.githubusercontent.com/409279/67162505-82ce8e00-f332-11e9-94c8-85f005149308.png)
