### ISSUE TITLE
Megan's request for button style

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#289]
@meganelizabethphillips  would like buttons to be square with sharp corners and no drop shadow; she’d also wants the buttons to highlight or something on hover; she was looking at this specifically on the [sponsors page](https://live-lfeventsci.pantheonsite.io/about/sponsor/); she likes the buttons on [this page](https://events.linuxfoundation.org/events/open-source-summit-europe-2019/attend/venue-travel/)

**Comment by andycochran** [comment]
The buttons used to be square-cornered without drop shadows. I think there was a previous request by @dankohn to make them look more clickable, so we added rounded corners and drop shadow. 

However, they definitely should have a hover effect. I'll go ahead and fix that bug…

**Comment by andycochran** [comment]
Okay, the hover effect isn't possible with the Gutenberg button block that's being used here. By default, buttons are `#0099cc` (and `#0082ad` when hovered). These styles are applied in the CSS file. The Gutenberg button block adds an inline style which overrides the color of the button. You can't do hover colors with inline styles. Why not use the default button color which has a hover style? 

I have pushed a fix that allows you to choose the squared button option:

![image](https://user-images.githubusercontent.com/409279/66261047-dc608580-e794-11e9-9453-9c7afa006e8c.png)

**Comment by cjyabraham** [comment]
@meganelizabethphillips please use the stackable button which has all these features.
