### ISSUE TITLE
Header disappears on mobile

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#292]
1. Start on the [homepage](https://live-lfeventsci.pantheonsite.io) or any homepage section
2. Scroll down somewhat and then click on an external Event that takes you off the homepage
3. Hit the back button
4. Scroll up and you'll see the homepage topnav is gone
![Screenshot_20191004-214024](https://user-images.githubusercontent.com/463160/66222982-935cf280-e6fc-11e9-96ce-642ca3322bed.png)

**Comment by cjyabraham** [comment]
Basically anytime the page loads on mobile in a scroll position in which the header is not visible, when you scroll up to see the header, it's not there.

**Comment by cjyabraham** [comment]
I just realize that in these cases the topnav will appear at the bottom of the page:

<img width="318" alt="Screen Shot 2019-10-05 at 11 19 15 AM" src="https://user-images.githubusercontent.com/463160/66249733-09477500-e762-11e9-96a5-a218eb6de21e.png">

**Comment by andycochran** [comment]
Looks like this is a known issue w/ Foundation: https://github.com/foundation/foundation-sites/issues/11098

I've patched it.

**Comment by cjyabraham** [comment]
This is fixed now on mobile portrait view but looks like it's still a problem on landscape view.

**Comment by andycochran** [comment]
Fixed. 😎 

I'd just patched it for small screens. But since the header is sticky at large screens, the fix didn't account for medium screens. Easy fix.

**Comment by cjyabraham** [comment]
I'm seeing this happening again.  Any reason why this may have returned?  It doesn't happen all the time but I've seen it a few times now in the last 2 days:
<img width="745" alt="Screen Shot 2019-11-15 at 6 32 25 PM" src="https://user-images.githubusercontent.com/463160/68940654-5ba29980-07d6-11ea-8044-a15c0f9189d6.png">

**Comment by andycochran** [comment]
Fixed. Wasn't a regression. The previous fix only took care of the main menu, not the event menus.

**Comment by cjyabraham** [comment]
I'm finding the multi-part menu is still disappearing.  Try [going here](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/program/super-long-multi-part-page/#aws-container-day) and then scroll up and you'll see it's gone:
<img width="326" alt="Screen Shot 2019-11-17 at 9 24 19 AM" src="https://user-images.githubusercontent.com/463160/69002087-0d97ae00-091c-11ea-84b8-3ad426fc27ea.png">

**Comment by andycochran** [comment]
Okay, this should really be fixed now.

- The first "fix" was scoped to the main menu
- The second "fix" also included event menus
- This fix is a more general refactor of Foundation's Sticky, which applies to all of our instances of Sticky. Instead of using the menu classes to target the CSS selectors, I'm targeting all Sticky instances that get stuck on large screens.

**Comment by cjyabraham** [comment]
Looks great.  thx.
