### ISSUE TITLE
Keyboard pops up on iPad when I select a filter

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#293]
When I select a filter on the [calendar page](https://live-lfeventsci.pantheonsite.io/about/calendar/) the keyboard on the iPad pops up unnecessarily, at least in BrowserStack.  Can this be prevented:

<img width="436" alt="Screen Shot 2019-10-05 at 11 22 56 AM" src="https://user-images.githubusercontent.com/463160/66249774-95f23300-e762-11e9-8937-8fdf4057bbbb.png">

**Comment by andycochran** [comment]
I don't understand the problem. This is by design. The keyboard pops up because this is a typeahead input, wherein user-entered text filters the select options.

**Comment by cjyabraham** [comment]
Ah!  Brilliant :)
