### ISSUE TITLE
Fix "No Results Found"

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#295]
If you go [here](https://live-lfeventsci.pantheonsite.io/about/calendar/archive/?_sft_lfevent-category=hyperledger-events&_sft_lfevent-country=russia) You'll see "No Results Found" that isn't fully on the screen on an iPad or when the screen is narrowed:

<img width="973" alt="Screen Shot 2019-10-05 at 2 06 43 PM" src="https://user-images.githubusercontent.com/463160/66251351-61d63c80-e779-11e9-9d9e-e25c16341f42.png">

**Comment by andycochran** [comment]
5510408df9402aa66e58bd6b5e052b98b7d643f8 should fix this. Please confirm in prod before closing.

**Comment by cjyabraham** [comment]
confirmed
