### ISSUE TITLE
Gutenberg button not centered in editor

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#297]
Any idea why this button is not centered [in the editor](https://live-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=531&action=edit) but is centered [in the preview](https://live-lfeventsci.pantheonsite.io/?page_id=531&preview=true)?

**Comment by andycochran** [comment]
It looks like this style…
```
.wp-block-button-wrapper {
    display: table;
}
```
— which is coming from `/wp-content/plugins/gutenberg/build/block-library/editor.css` — is preventing the alignment setting from showing in the editor. 

This might just be a bug in Gutenberg. I don't think there's anything we're doing to cause this.

**Comment by cjyabraham** [comment]
Ok.  When we upgrade the plugin, hopefully this should resolve itself.  I'll leave this open for now...

**Comment by cjyabraham** [comment]
This appears to be fixed now, both for regular buttons and stackable buttons.
