### ISSUE TITLE
Experiment with layouts of an Event main page that has only a bit of content

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#306]
You can experiment with the [new AGL site](https://events.linuxfoundation.org/wp/wp-admin/post.php?post=531&action=edit).

**Comment by andycochran** [comment]
A couple options… 

https://dev-lfeventsci.pantheonsite.io/automotive-grade-linux-all-member-meeting/

https://dev-lfeventsci.pantheonsite.io/automotive-grade-linux-all-member-meeting-2/

**Comment by cjyabraham** [comment]
Thanks.  I think I like the first one best.  @meganelizabethphillips what do you think?

**Comment by meganelizabethphillips** [comment]
@cjyabraham @andycochran totally agree - the first one is great. Thanks so much for pulling this together.
