### ISSUE TITLE
Add these instructions to the readme to get local instance to trust SSL

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#310]
To get your browser to trust the Lando SSL so you don’t get the warnings:
1. Run the commands [here](https://docs.lando.dev/config/security.html#trusting-the-ca) to get MacOS to trust the CA
2. Go into Keychain Access and set the *.lndo.site certificate to “Always Trust”.  See [screenshot](https://drive.google.com/file/d/1S9Ao8uJC983ZwdjwoBJ6GZsfi34yR-0H/view).

Get Andy or James to test them.

**Comment by cjyabraham** [comment]
Update made.  Waiting for Andy to test.

**Comment by cjyabraham** [comment]
@andycochran can you test out these instructions to see if they work for you?  It's [step 9 here](https://github.com/LF-Engineering/lfevents#lando-setup).  This is assuming you haven't already got this working.

**Comment by andycochran** [comment]
Worked for me. I stopped Lando and quit my local server for the theme before running the command, and I didn't have to do the Kaychain Access step (it was already set to "Always Trust").
