### ISSUE TITLE
Experiment with different design treatments for multi-part page with long titles

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#318]
As per our discussion on the group call, see if you can make the multi-part page work better when we have a lot of sections and long titles.  Try truncating the titles after two lines and stuff like that.

**Comment by andycochran** [comment]
Pushed up a branch called `318-multipart-menu-ellipsis` with the following changes on large screens (when the menu is alongside the content): 

- Makes the menu slightly wider and content area slightly narrower 
- Automatically truncates the menu item titles with an ellipsis 
- Upon hover, a menu item shows the full title

![image](https://user-images.githubusercontent.com/409279/67167859-3011c800-f36c-11e9-94e1-c70fbe18ecc7.png)

**Comment by cjyabraham** [comment]
@meganelizabethphillips what do you think of [this solution](https://pr-329-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/program/super-long-multi-part-page/#cloud-native-storage-day-hosted)?  I don't love it but we could have it as an option for pages with a lot of long titles.

**Comment by cjyabraham** [comment]
comments from @dankohn :
1. Move to single spacing in the TOC.
2. Use a bullet or other visual indicator to make clear that each TOC entry is separate,
3. Leave a little less whitespace on the far left?

**Comment by meganelizabethphillips** [comment]
@andycochran @cjyabraham thanks for your work on this. I don't love this option either - my issue is really with the double scrolling. I just think its a lot to look at. Maybe we could do some testing within the events team and see what they think? The other issue is that i receive this information (colocated events for example) on a rolling basis, so I won't know that I'm getting a lot of long titles until the page is live with other content. How easy is it to "switch" into this from the regular long page format and have all the information carry over?

**Comment by dankohn** [comment]
We worked hard on this multi-page design and I think it's quite good. Could we please launch with this, and then try other approaches if we get feedback that it's problematic. I think it's a huge improvement over what we have now.

However, I would like to cherry pick this fix: https://github.com/LF-Engineering/lfevents/issues/223

**Comment by cjyabraham** [comment]
I agree with @dankohn that our current efforts are likely better spent on other tasks at the moment.  @meganelizabethphillips feel free to push back but I'll mark this as a nice-to-have issue we can pull up if there arises a stronger case for it.

**Comment by cjyabraham** [comment]
Closing this for now as what we have seems to be meeting our needs.
