### ISSUE TITLE
Style the sidebar in lfasiallc homepage

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#319]
I've put the [QR code and some text there](https://live-lfasiallcci.pantheonsite.io).  Wait on this until we get confirmation on what content we want in there.

**Comment by cjyabraham** [comment]
Angela has okayed the content.

**Comment by cjyabraham** [comment]
I have replaced the png QR code with an svg.  I put a width="150px" on the <img> tag but feel free to do it in CSS if that's the better way.

**Comment by cjyabraham** [comment]
Looking at it now, I'm really not sure this needs much styling.  Maybe just center the QR code in the middle of the column?

**Comment by andycochran** [comment]
I like it as-is.

**Comment by cjyabraham** [comment]
Just curious, is setting the width="150px" on the QR code right on the <img> element, as I have done, problematic in any way?  How would you have done it?

**Comment by andycochran** [comment]
Nope. This is fine. All images have `max-width:100%` applied by default in the CSS which will override the inline `width` attr so it can't spill out of the container or break the layout.
