### ISSUE TITLE
Change Oceania to Asia Pacific

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#320]
After consideration, I'd like to take Angela's suggestion and merge Asia and Oceania into Asia Pacific. I think items under Oceania get lost at the bottom.

**Comment by cjyabraham** [comment]
Ok, done.  So Australia is now listed under Asia Pacific with all the other Asia countries.

**Comment by cjyabraham** [comment]
Now that we're going with the full list of countries, should we revert to keeping Asia and Oceania separate, or leave them together as Asia Pacific?

**Comment by dankohn** [comment]
Asia Pacific, please.

Note that countries should only show when there is an event with that
country, as it works now.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>
