### ISSUE TITLE
Can we find a better way of doing bullets?

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#326]
When we put bullets in [a page like this](https://events.linuxfoundation.org/?page_id=845) we have to put them in a container so that the bullets don't go outside the left margin.  But inside the container, we have too much top and bottom margins.  Can we find a better way of doing bullets?  Note that bullets can be done using the List block or as just bullets inside a Paragraph block.  @meganelizabethphillips has used both ways on that page and the bullets are different sizes so likely we should standardize with one way.

Whatever you implement, be careful not to affect [bullets that do look](https://events.linuxfoundation.org/about/sponsor/) good [right now](https://events.linuxfoundation.org/about/sponsor/).

**Comment by cjyabraham** [comment]
@meganelizabethphillips bullets should no longer need a container to indent them correctly so this should solve your problem you were having with the container spacing.

**Comment by meganelizabethphillips** [comment]
@cjyabraham thanks for fixing this!

**Comment by meganelizabethphillips** [comment]
@cjyabraham I took them out of containers and made them both lists - still not very indented:
https://events.linuxfoundation.org/?page_id=845&preview=true
Anything different I need to do here?

**Comment by cjyabraham** [comment]
@meganelizabethphillips that link doesn't work for me.  Can you send me the public-facing url and I'll take a look?

**Comment by meganelizabethphillips** [comment]
@cjyabraham its the same page as before - https://events.linuxfoundation.org/?page_id=845

**Comment by cjyabraham** [comment]
@andycochran as discussed on our call, please indent the bullets slightly so that they look more like [what we had on the old site](https://events19.linuxfoundation.org/events/embedded-linux-conference-europe-2019/attend/scholarships/).
