### ISSUE TITLE
Add second Sponsor CTA for Chinese prospectus to kubecon splash page

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#328]
Add buttons to the lfasiallc.com homepage for both English and Chinese versions of the prospectus.  The English version is on the main Events site.  Chinese version attached:
[sponsor-cncf-ch-20191018.pdf](https://github.com/LF-Engineering/lfevents/files/3746174/sponsor-cncf-ch-20191018.pdf)

Get Jenny to translate the button text.

**Comment by cjyabraham** [comment]
@dankohn @meganelizabethphillips 
Do we want a separate sponsor page for this, similar to how we have it on [the main site](https://events.linuxfoundation.org/about/sponsor/)?  Alternatively we could put them on [the about us page](https://live-lfasiallcci.pantheonsite.io/about/about-us/)?

**Comment by dankohn** [comment]
I’d rather have the download links right on the homepage but it’s not my call.

**Comment by cjyabraham** [comment]
In that case, we could fit them in in the top blurb or on the sidebar?  @meganelizabethphillips ?

**Comment by meganelizabethphillips** [comment]
@cjyabraham @dankohn spoke with Angela about this and we think that the sidebar would work nicely while this is the only event up on the site. Once more events populate, we need to remove it or find a place we want to add all the event prospectus' directly. I think the "sponsor" CTA associated with each event does the trick generally speaking.

**Comment by dankohn** [comment]
I don't think we need to bother with the sidebar if it's just temporary.

Could we support two sponsor buttons, one for "Sponsor (English prospectus)" and one (in Chinese) that says "Sponsor (Chinese prospectus"? That's a solution that would likely work for multiple events.

**Comment by cjyabraham** [comment]
I did a quick survey of Events listed on the [main site](https://events.linuxfoundation.org) and all Sponsor buttons I looked at go to a Sponsor page on the Event site.  Wouldn't that page be the best place to have English and Chinese buttons that link to their respective prospectus?

**Comment by dankohn** [comment]
Fine with me. But the button should then say `赞助商 Sponsor`.

**Comment by cjyabraham** [comment]
@meganelizabethphillips assuming you're ok with this solution, I'll assign to you to implement.

**Comment by meganelizabethphillips** [comment]
@cjyabraham looks like this was already implemented on the splash page? Let me know if I'm missing something

**Comment by cjyabraham** [comment]
@dankohn wants two buttons, one for the English and one for the Chinese prospectus.

**Comment by cjyabraham** [comment]
Alex did it.
