### ISSUE TITLE
Add "Past [category name] Events" to the All Events menu

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#333]
put it just above the "Past Events" option

**Comment by cjyabraham** [comment]
I think that if we have "Past [category name] Events" we don't also need a "Past Events" link.  Wouldn't they be redundant?  Who would go to "Past Events" when they can go to the past category Events?  And when they go to the category Events they can just hit "reset" to see all Events anyway.  

What do you think @dankohn and @meganelizabethphillips?    

[I've got it working on the dev site](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/).

**Comment by dankohn** [comment]
This isn't right yet. `Past KubeCon Events` is for attendees to see speaker and sponsor lists in the past and sometimes to download old slides. It should use the cropped KC+CNC logo: https://github.com/cncf/artwork/blob/master/examples/other.md#kubecon--cloudnativecon-cropped-logos

Then, below it, All Past LF Events is essentially a form of cross-promotion. I agree that it's not as important as All Upcoming Events, so I'd be open to killing it.

**Comment by cjyabraham** [comment]
I'm interested in @meganelizabethphillips and @andycochran POV on having both "Past KubeCon Events" and "All Past Events".  Do we need both or just the "Past KubeCon Events" since once they are there it's easy to reset the filter to see all Events?

@dankohn can we get svg logos for all of our categories?  Or, if no logo, we can fall back to showing the Linux Foundation Events logo [as shown here](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/)?

**Comment by dankohn** [comment]
I'm inclined to leave All Upcoming LF Events as cross-promotion but removing All Past LF Events in favor of All Past KubeCon events.

I'll open a Slack with Craig to get the logos.

**Comment by cjyabraham** [comment]
Thinking about this more, I think we should go without a logo at all for "All Past KubeCon Events", in all cases.  

In almost all cases there will be 2 related Events in that menu dropdown and such Events will share a very similar logo to the overall category of Events.  In the case of [Kubecon](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/) that means we'll already have two large Kubecon logos in that menu dropdown.  I don't think we need a third to go with the words "All Past KubeCon Events" . I think it would be cleaner just to have the text "All Past KubeCon Events" in its own menu item at the bottom of that menu.

I also don't think we need another instance of The Linux Foundation logo, for cases when we don't have a category logo.  We already have it at the top of the menu and I think it would be redundant and possibly confusing to have it again at the bottom before we say "All Past [category name] Events".

Any thoughts?

**Comment by cjyabraham** [comment]
In the AGL case it would look like this:
<img width="538" alt="Screen Shot 2019-10-27 at 9 39 14 AM" src="https://user-images.githubusercontent.com/463160/67628754-ac8d3500-f89d-11e9-9376-7242befc60b0.png">

**Comment by dankohn** [comment]
Sounds good. 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c
