### ISSUE TITLE
Find a good background image for our job board

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#334]
Here's our [new CNCF job board](https://cncf.jobboard.io).  Can you search for a better background image.  You can search in the the [CNCF flickr accounts](https://www.flickr.com/photos/143247548@N03/albums).  Feel free to add a tint or whatever.  We can also override the CSS for the text as well.

**Comment by andycochran** [comment]
I kinda like this one that's there now. It's a network. I like how the soft focus creates depth. 

![image](https://user-images.githubusercontent.com/409279/67915162-9070e880-fb68-11e9-9998-3ebc06b9e2d2.png)

It is a bit pixelated on large screens tho. 

![image](https://user-images.githubusercontent.com/409279/67915238-c1e9b400-fb68-11e9-86ee-d21ea6acdc3b.png)

**Comment by dankohn** [comment]
I can survive with that, but I find those images kind of "generic Silicon Valley startup". We have so many great pictures; I was hoping to find one to use.

**Comment by cjyabraham** [comment]
@andycochran could you do a quick search and offer a couple alternatives so that we're sure we're making the right decision here?  I don't love that this image is so common across the web and people have possibly seen it elsewhere.

**Comment by cjyabraham** [comment]
Does anyone like this one better?  It uses [this image](https://www.cncf.io/wp-content/uploads/2016/09/cncf_slide_bg1.jpg).  I think it's more unique than the other since I couldn't find it on google.
<img width="1440" alt="Screen Shot 2019-11-03 at 2 02 33 PM" src="https://user-images.githubusercontent.com/463160/68081570-ade0d380-fe42-11e9-9363-68ed073d3358.png">

**Comment by cjyabraham** [comment]
Andy's comment:
"I scoured through all the cncf Flickr images and I don’t see one appropriate for use here. They’re all either too conferency, all dudes, too specific a moment, or people slouching sleepily in seats. I think an abstract image like you have is better. I get the reservations using a generic stock image. But the set on Flickr probably won’t be helpful. Is there a particular goal for this image?"

**Comment by cjyabraham** [comment]
I replaced the image with [this final one](https://jobs.cncf.io/).
