### ISSUE TITLE
Split Chinese menu titles

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#345]
Menu titles [for Chinese sites](https://events19.lfasiallc.com/events/kubecon-cloudnativecon-china-2019/) should have the Chinese on one line and the English on the next line.  To accomplish this, we could split based on a "|" character.

**Comment by cjyabraham** [comment]
@meganelizabethphillips you can insert a `<br>` in the page title where you want to break the line, same as you were doing on the old site.

**Comment by meganelizabethphillips** [comment]
Done! Thank you!
