### ISSUE TITLE
Figure out why the image in the text-on-image block is so huge

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#346]
See the block on [this page](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/).  How do we make the image shorter?

**Comment by andycochran** [comment]
I don't see the problem. It looks exactly how it was designed to look. The more text you add, the taller the image will grow. Remove text and it'll be shorter. 

### Original
![image](https://user-images.githubusercontent.com/409279/68536401-59e15d80-0320-11ea-999f-1c382e3d8469.png)

### More text 
![image](https://user-images.githubusercontent.com/409279/68536408-7bdae000-0320-11ea-8f27-b69450405775.png)

### Less text 
![image](https://user-images.githubusercontent.com/409279/68536455-10454280-0321-11ea-8146-27df8648197e.png)

**Comment by cjyabraham** [comment]
Fair enough.  @meganelizabethphillips are you ok with this or would you still prefer the image to be shorter relative to the amount of text?

**Comment by andycochran** [comment]
I could reduce the amount of top/bottom padding on the image so that the text takes up more of the height of the image. But I think the generous padding is necessary for this component. Otherwise you might as well just put the image next to the text instead of under it.

**Comment by meganelizabethphillips** [comment]
That's fine. It just looked large compared to the rest of the items on the homepage. I wanted to confirm I understood how this worked in case there were questions raised to me about it. Thanks for confirming.

**Comment by cjyabraham** [comment]
Ok.  I'll close for now.  Let us know if you do end up wanting any adjustments to it.
