### ISSUE TITLE
Improve style of flickr "show more" button

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#348]
Can we style the Show More button on the Flickr gallery to inherit theme colors or make it smaller or something.  @meganelizabethphillips  thinks that it doesn’t quite work and is not consistent with the other buttons on [this page](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/)(you'll need to be logged in).

**Comment by andycochran** [comment]
There's not a way for this button to inherit theme colors. Themed buttons are given inline classes and styles. This button is added to the markup by the Flickr plugin, so there's no opportunity to theme it. 

We're already overriding the default styles of this plugin's button style. But that's global, not theme-specific. 

Regardless, I don't see a problem with its style. I think it's okay that it is different than other themed buttons — it serves a specific function that's limited to the Flickr gallery, as opposed to linking to other pages.

**Comment by cjyabraham** [comment]
Ok.  I'm fine with the button too.  @dankohn do you have an opinion on this?

**Comment by dankohn** [comment]
No opinion

**Comment by cjyabraham** [comment]
@meganelizabethphillips what were you envisioning for how you wanted these buttons styled?

**Comment by cjyabraham** [comment]
I'll close this since it's been sitting idle for a while but @meganelizabethphillips feel free to re-open if you want.
