### ISSUE TITLE
Improve currency formatting on registration block

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#349]
[Registration block with two currencies](https://www.lfasiallc.com/kubecon-cloudnativecon-china/register/) sometimes splits them up on two lines, sometimes keeps them on the same line.  Can we be consistent.

**Comment by cjyabraham** [comment]
@meganelizabethphillips this is due to the length of the amounts.  If you want to force a line break you can put <br> in the field.  Is that adequate?

**Comment by meganelizabethphillips** [comment]
@cjyabraham this fixed the currency issue and the rate type issue, but now you can not see the date ranges for each rate type. Can this be looked at urgently? Thank you!

**Comment by cjyabraham** [comment]
That is a separate issue #350
