### ISSUE TITLE
Figure out why the banner images look a bit blurry throughout this site

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#351]
On [this page](https://www.lfasiallc.com/kubecon-cloudnativecon-china/venue-travel/) the image that is being loaded in the header banner is [this one](https://www.lfasiallc.com/wp-content/uploads/shanghai-small-1200x675.jpg) instead of [the original](https://www.lfasiallc.com/wp-content/uploads/shanghai-small.jpg).  Why doesn't it favor the original image?

Code for this is found [here](https://github.com/LF-Engineering/lfevents/blob/master/web/wp-content/themes/lfevents/singular.php#L121).

**Comment by meganelizabethphillips** [comment]
@cjyabraham was this resolved somehow? It still looks blurry to me

**Comment by cjyabraham** [comment]
Which one still looks blurry?
