### ISSUE TITLE
Add Past Events button to bottom of Upcoming Events calendar

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#353]
Could we please add a "Past Events" button to the bottom of https://events.linuxfoundation.org/about/calendar/ similar to the button at the bottom of https://events.linuxfoundation.org/. 

And an Upcoming Events button to the bottom of https://events.linuxfoundation.org/about/calendar/archive/.

**Comment by cjyabraham** [comment]
I think @dankohn wanted the button in the same style as the button at the bottom of [the homepage](https://events.linuxfoundation.org/)(that big grey button).

**Comment by andycochran** [comment]
Ah. That's a little more involved that what I did. I kinda like the way I've made the top and bottom buttons the same (they're the same function). @dankohn, does this not solve the issue?

**Comment by dankohn** [comment]
I'm OK with what you've done.
