### ISSUE TITLE
Review design of new kubecon sites and propose improvements

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#356]
https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america-2/
https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/

**Comment by andycochran** [comment]
These look like they're expandable but they're not. 

![image](https://user-images.githubusercontent.com/409279/68536634-b85c0b00-0323-11ea-8dbf-13f5244890e6.png)

**Comment by andycochran** [comment]
I put the sample letter in a container that makes it look like a letter. 

![image](https://user-images.githubusercontent.com/409279/68536687-b2b2f500-0324-11ea-90fb-00c359e97b32.png)

**Comment by andycochran** [comment]
The color on these headers makes them look like links. I'd just make them larger and the default text color. 

![image](https://user-images.githubusercontent.com/409279/68536699-f0178280-0324-11ea-9036-a206ba109fcf.png)

**Comment by cjyabraham** [comment]
@meganelizabethphillips see Andy's comments above.

**Comment by cjyabraham** [comment]
Assigning to @meganelizabethphillips .  Feel free to close when done with this feedback.
