### ISSUE TITLE
Style the newsletter form

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#358]
[Here's the code](https://docs.google.com/document/d/1JI1xH-q7FMWXlVghAALoKB3V9562tMLr7J3WoiyyzHs/edit?ts=5dc5cb86).

- [x] Style it on the [kubecon NA page here here](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america-2/)
- [x] Insert it somewhere and style it on the [kubecon China page here](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/)

**Comment by cjyabraham** [comment]
Maybe we should use a gravity form and have it submit to SF using [this method](https://docs.gravityforms.com/gform_form_tag/).  Let's discuss.

**Comment by meganelizabethphillips** [comment]
Thank you for this! Looks SO much better!
