### ISSUE TITLE
Improve the styling and validation on the newsletter forms

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#363]
Now that we are committed to delivering forms without using Gravity Forms, improve the styling and validation on these newsletter forms.  Maybe add placeholder text instead of labels, etc.:
- [Kubecon NA](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america-2/)
- [Kubecon China](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/)

**Comment by cjyabraham** [comment]
@andycochran I've been refining [the form here](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/).  You'll first see the old gravity form and then the html form below it.  I've added a language choice that will be used just on the china site.

Could you improve the formatting of the language radio options?  Maybe make them go horizontally?  And add any other minor tweaks to the form that you feel would be good?  Then I can copy it back over to the live sites.

**Comment by dankohn** [comment]
Horizontal would be much better. Please change the Chinese label to say "中文 Chinese".

**Comment by andycochran** [comment]
Done (refresh to see). Looks like this: 

![image](https://user-images.githubusercontent.com/409279/68733639-47c42100-05a5-11ea-9c1c-6a8ef29c6136.png)

**Comment by cjyabraham** [comment]
deployed
