### ISSUE TITLE
Style this contract request form

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#371]
I'll take a first pass on [this form](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/sponsor/) and [this one](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america-2020/sponsor/) then pass on to @andycochran .

**Comment by cjyabraham** [comment]
@andycochran I've taken a first pass at the sponsor form [on the dev site](https://dev-lfeventsci.pantheonsite.io/test-sponsor-form/) applying some of the conventions you established in the newsletter form.  There is still work to do to space questions out appropriately etc.  Could you make this look good?  Then I can copy it into place on the lives sites.

**Comment by andycochran** [comment]
I've added some markup to adjust the spacing between the items.

**Comment by cjyabraham** [comment]
I don't think it looks as good as our [own sponsor form](https://events.linuxfoundation.org/about/sponsor/).  I see that form uses ul and li and a lot of gform styles.  Maybe I could mark this up like that?  Let's discuss on our call.

**Comment by cjyabraham** [comment]
The mobile view also has some problems:
<img width="311" alt="Screen Shot 2019-11-17 at 12 01 04 PM" src="https://user-images.githubusercontent.com/463160/69003311-08ddf480-0932-11ea-97c0-498f1c84cd7a.png">

**Comment by andycochran** [comment]
Labels for radio buttons aren't really meant to be that long. They don't do well as a paragraph of text — either the layout or the UX. I would advise the long text in parentheses not be included in the label, but follow after as help text. 

```
<li>
  <input type="radio" name="pokemon" value="Red" id="pokemonRed" required><label for="pokemonRed">Pokémon Red</label>
  <p class="help-text" id="whatispokemon">Pokémon Red is a role-playing video game developed by Game Freak and published by Nintendo for the Game Boy and Game Boy Color.</p>
</li>
```

Then the label won't awkwardly wrap to multiple lines.

**Comment by andycochran** [comment]
This is pointing out a larger concern: We need a standardized way of creating forms with solid/predictable markup. Leveraging a library like Gravity Forms gets us benefits of standardization among others. Just copying/pasting form markup, JavaScript, and CSS willy-nilly is going to be a continuous source of work and struggling against edge cases.

**Comment by cjyabraham** [comment]
I agree.  I think we're still in limbo regarding which way to go with these forms.  @dankohn made a call that he'd like us to do forms like this from scratch, without using Gravity Forms.  But then we heard from Marijana that, in fact, she is ok with us using Gravity Forms.  Finally, we hear that there are some significant changes to the forms yet to come, to enable tracking and progressive profiling, so I'm thinking we should wait for those features to be deployed before we commit to any one implementation.  

So, for now, I think we just want to do a decent enough job with the current forms and then wait to see what happens with these new features.

**Comment by cjyabraham** [comment]
This looks good enough for now.
