### ISSUE TITLE
Improve portrait mobile layout

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#374]
![image](https://user-images.githubusercontent.com/3083270/69892124-33d02d00-12d0-11ea-9caf-ed6b9ae556ad.png)

This seems like it would be better with the picture full width across the top and the text full width below it, at least in portrait mode.

**Comment by cjyabraham** [comment]
@meganelizabethphillips there's a block setting to "Stack on mobile" to address this:
<img width="720" alt="Screen Shot 2019-11-30 at 9 53 34 AM" src="https://user-images.githubusercontent.com/463160/69894806-8f91c900-1357-11ea-8dec-d31f69d068ad.png">


I've set it and added a spacer at the top of the text so now we have this on mobile:
<img width="496" alt="Screen Shot 2019-11-30 at 9 54 46 AM" src="https://user-images.githubusercontent.com/463160/69894809-9ae4f480-1357-11ea-897e-db4e4d991bcd.png">


Yay Gutenberg!!
