### ISSUE TITLE
Add a configurable link to View All Events menu

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#376]
A link text and url can be optionally configured to display another link, second in the list, on the View All Events menu.

**Comment by cjyabraham** [comment]
@andycochran can you add an external link icon to [this element here](https://github.com/LF-Engineering/lfevents/blob/master/web/wp-content/themes/lfevents/library/lfe-functions.php#L166) which gets inserted at the bottom of the View All Events menu.  See [demo on dev site](https://dev-lfeventsci.pantheonsite.io/kubernetes-forum-bengaluru/).

**Comment by andycochran** [comment]
This is done. IDK why the wraith tests are failing.

**Comment by cjyabraham** [comment]
The icon looks too close to the text I think:
<img width="312" alt="Screen Shot 2019-12-09 at 9 14 18 AM" src="https://user-images.githubusercontent.com/463160/70401971-5565ad00-1a64-11ea-9d14-fe796199a4d6.png">

Wraith looks like it's failing due to this:
<img width="889" alt="Screen Shot 2019-12-09 at 9 15 32 AM" src="https://user-images.githubusercontent.com/463160/70402011-7e863d80-1a64-11ea-8439-021f5c235c56.png">

I upgraded the WP Coding Conventions library.  You may need to run `lando composer update` to get them and make sure your editor is picking them up.

**Comment by cjyabraham** [comment]
deployed
