### ISSUE TITLE
Weird artifact on sponsor logo

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#378]
Can you figure out why there's this weird artifact showing up on the [sponsor logo here](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/).  I notice when I deactivate the "width" css it disappears:
<img width="686" alt="Screen Shot 2019-12-08 at 12 04 53 PM" src="https://user-images.githubusercontent.com/463160/70384584-33f8b880-19b3-11ea-9123-432efff70ee5.png">

**Comment by dankohn** [comment]
It's a flaw in the original SVG. Sometime companies try to put several images in one SVG and then use viewbox to crop (which is always a bad idea).

Please just switch it to use https://landscape.cncf.io/logos/portworx.svg.

**Comment by cjyabraham** [comment]
Great.  This is fixed.  You may need to shift-reload your page to get the new image.
