### ISSUE TITLE
Improve styling of Request a Contract form

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#379]
Can you put some more work into this form to make it look as good as [this form](https://events.linuxfoundation.org/about/sponsor/).  Here are some suggestions:
- make form labels all the same size as the "Billing address" text, so that they all look to be at the same level of importance
- move the "Billing address" label down a bit so it's closer to the fields it is introducing
- adjust the spacing slightly for the intro label for the radio buttons so they are a bit more obviously grouped
- change style of "Submit" to look like [the one here](https://events.linuxfoundation.org/about/sponsor/) and add a bit of top padding so that it's not so close to the checkbox above it.

We will be using this form on various other events so want to make it look as good as possible before we turn it into a re-usable block.  We will also be wanting to implement various other forms this way following [this strategy](https://docs.google.com/spreadsheets/d/1h9SudSuu5Th7nZQ0ytJ4qzugFMtWKEVcQDHJkfVcS8Q/edit#gid=1114204169) so whatever styles you can establish, we can re-use for other forms.

**Comment by andycochran** [comment]
Where is the Request a Contract form? You've linked to example you want it to look more like. But I can't find the one that needs changing.

**Comment by cjyabraham** [comment]
[Here is one of the instances](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/sponsor/).

**Comment by dankohn** [comment]
Could you please default to a greyed out "State" instead of a selected Alabama. https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/sponsor/

**Comment by andycochran** [comment]
I've added a new first option to the State `<select>` element: 
`<option value="" disabled selected>State</option>`

This is better than defaulting to Alabama. Unfortunately, making just the one option grey isn't so easy. It'd require custom JS and event listeners on the form. CSS-only methods don't have much browser support.

**Comment by dankohn** [comment]
LGTM
