### ISSUE TITLE
Dynamically generate better card preview images

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#380]
As can be seen on https://cards-dev.twitter.com/validator we're currently using the hero image as the preview. For nearly all events, the hero image is a JPG and the logo is an SVG. We should dynamically create a PNG representing the overlay of the SVG logo on to the JPG and use that PNG as the preview image. 

See https://louisem.com/217438/twitter-image-size for recommended image sizes
>The Twitter card images shown in the feed are 1.91:1. Recommended: 1200 x 628

**Comment by cjyabraham** [comment]
@meganelizabethphillips do you think this would be useful?  I wonder whether it might not look good in some cases, depending on the featured image.  Have you been setting the social image for the Events with an image from Alex?

**Comment by meganelizabethphillips** [comment]
@cjyabraham The team hasn't had a chance to develop these yet. I am sending a message out to the department this week about requesting graphics from CS for social purposes that are more like proper snackables. It would be cool if it could auto pull from the hero image, logo, event dates, and event location (as that is all we would need on them) and create an auto-generated card so that they were all standard looking but I wouldn't say its a necessity!

**Comment by cjyabraham** [comment]
Ok.  Given that you already have that in your workflow and automating this would be very difficult with a sub-optimal result, I'll file this away as a nice-to-have for now.

**Comment by cjyabraham** [comment]
@thetwopct found [this plugin](https://socialimagegenerator.com/) recently which could be a way of automating this.

**Comment by meganelizabethphillips** [comment]
Right now, these are designed by creative services for us so I think it's
okay to keep our process as is! Thanks for sharing though :)

Megan Knight (Phillips), PMP
Events Web Project Manager
The Linux Foundation
1 Letterman Drive
Building D, Suite D4700
San Francisco, CA 94129



Why Attend Linux Foundation Events <https://youtu.be/X_rLxfmLlYY>
Why Sponsor Linux Foundation Events <https://youtu.be/Rr-9cIH42fE>

**Comment by cjyabraham** [comment]
Closing this as snackable production is part of the Creative Services job in the Event production pipeline. I think having a human fine-tune these is worth the extra effort over something that could be automated.
