### ISSUE TITLE
Alphabetize images in Media Library chooser to help with finding sponsor logos

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#388]
Please modify https://events.linuxfoundation.org/wp/wp-admin/post.php?post=2058&action=edit to show in alphabetical order.

**Comment by cjyabraham** [comment]
The images are already in alpha order within the sponsor blocks.  Are you referring to something else?

**Comment by dankohn** [comment]
Yes, I'm suggesting that it would be nice if the images were in alpha order when picking them from the image chooser.

**Comment by cjyabraham** [comment]
Ok.  I find the best way to find a sponsor logo is to type the name of the sponsor in the "Search media items" box.  You can also limit the view to just sponsors by choosing "Sponsor" from the category dropdown.  I could see that alphabetizing it might be helpful as well.

**Comment by cjyabraham** [comment]
This is no longer relevant as we have changed the way we store sponsors.  Listing them alphabetically [is now possible](https://events.linuxfoundation.org/wp/wp-admin/edit.php?post_type=lfe_sponsor&orderby=title&order=asc).
