### ISSUE TITLE
Improve line-wrapping in schedule-at-a-glance block

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#393]
On the [kubecon schedule-at-a-glance block](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/program/schedule-at-a-glance/), we want to try and keep the description of the event all together so that it doesn't wrap under the time.  Here is the problem:
<img width="1134" alt="Screen Shot 2019-12-17 at 5 46 31 PM" src="https://user-images.githubusercontent.com/463160/71040691-2f3fad00-20f5-11ea-982f-fbdf73ae398f.png">

And we want it to wrap more like this (but with the spacing improved):
<img width="1138" alt="Screen Shot 2019-12-17 at 5 46 58 PM" src="https://user-images.githubusercontent.com/463160/71040715-3e265f80-20f5-11ea-9a5d-a0a3a4d641ab.png">

And yet it has to be easily editable.

**Comment by cjyabraham** [comment]
[Something like this could work](https://stackoverflow.com/questions/2833068/text-indent-after-the-first-line-in-a-paragraph) though our markup isn't enough right now to accommodate this since we use `<br>` instead of `<p>` within the block.

**Comment by andycochran** [comment]
Looked into this… 

`text-indent` would be a brittle solution, as it would depend on the content. I think there are a few solutions: 

1. (Simple) Intentionally put the times and details on their own lines. This can be done in Gutenberg. 
  ![image](https://user-images.githubusercontent.com/409279/71323857-c9ad4100-24a5-11ea-8d9b-13340f123c02.png)
2. (Simple w/ revised design) Put the times and details in their own cells. 
  ![image](https://user-images.githubusercontent.com/409279/71323955-17767900-24a7-11ea-9170-549dca755413.png)
3. (Complex) Create a custom Gutenberg block where we control the markup, putting the times and details in their own containers which can have layout classes.

**Comment by dankohn** [comment]
Could you please propose a design that would work well with these more complicated schedule-at-a-glance instances:

https://events19.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/
https://www.lfasiallc.cn/kubecon-cloudnativecon-open-source-summit-china/program/schedule-at-a-glance/

I'm inclined to propose a 2a, where the top two cells and bottom two cells in the first column are merged.

**Comment by andycochran** [comment]
I'm thinking it'd be better to have a table for each day. Date as a header above the table. Two columns: time on left, details on right.

**Comment by dankohn** [comment]
I'm open to that. Could you please mockup the more complicated examples?

**Comment by andycochran** [comment]
After attempting various solutions for the schedule-at-a-glance design using tables, every method shows flaws with awkward wrapping, excessive spacing, etc. This data isn't best presented in tables, since they prevent responsive layout. I propose (instead of using tables) creating a custom Gutenberg block, which would allow us to present the data with custom markup with responsive styles. @dankohn agreed this would be a great solution. 

(Will prioritize this after forms.)

**Comment by dankohn** [comment]
My proposed solution would support cells and allow data entry to do things like:

![image](https://user-images.githubusercontent.com/3083270/71783900-2be46680-2fbb-11ea-86c5-a43ad77fa852.png)

That is, support multiple languages for the same field, and allow merged fields to avoid needing to repeat text.

**Comment by cjyabraham** [comment]
I did a quick survey of how Schedule-at-a-Glance is being used.

1. 17 are using it with just two columns: date or time and description.  Eg:
<img width="832" alt="Screen Shot 2020-02-04 at 9 54 09 AM" src="https://user-images.githubusercontent.com/463160/73709668-50576e00-4734-11ea-92ee-03373b6f186c.png">
<img width="918" alt="Screen Shot 2020-02-04 at 9 54 50 AM" src="https://user-images.githubusercontent.com/463160/73709691-67965b80-4734-11ea-8b28-2cbaf533022e.png">

2. 4 are using 3 columns: date, time and description
<img width="808" alt="Screen Shot 2020-02-04 at 9 59 16 AM" src="https://user-images.githubusercontent.com/463160/73709906-0622bc80-4735-11ea-96cb-824b1cb6395b.png">

It appears to be only the Kubecons for which this issue is relevant.  How about this solution:
- for the case when there's only one description that is too long, we could use a * to add a footnote.  This would fix the line-wrap issue with all widths except mobile:
<img width="1172" alt="Screen Shot 2020-02-04 at 10 03 59 AM" src="https://user-images.githubusercontent.com/463160/73710141-c01a2880-4735-11ea-80fa-a7d9fc864b42.png">

- for the 1 case when there is a very long description, multiple languages, etc, we use Andy's previously proposed solution:
  ![image](https://user-images.githubusercontent.com/409279/71323857-c9ad4100-24a5-11ea-8d9b-13340f123c02.png)

**Comment by dankohn** [comment]
I want to avoid footnotes. Could you please show how your two column solution would look with complex two language text like https://events19.linuxfoundation.cn/events/kubecon-cloudnativecon-china-2019/

**Comment by cjyabraham** [comment]
Sure.  [I've mocked it up here](https://sandbox-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/)

**Comment by cjyabraham** [comment]
@dankohn has decided to go with the above suggestion.  I have updated all three kubecons:
- https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/ and https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/program/schedule-at-a-glance/
- https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/
- https://www.lfasiallc.cn/kubecon-cloudnativecon-open-source-summit-china/ and https://www.lfasiallc.cn/kubecon-cloudnativecon-open-source-summit-china/program/schedule-at-a-glance/
