### ISSUE TITLE
Improve apica scores

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#402]
all lfasiallc.cn files should serve from that domain and not from lfasiallc.com.  Some of the images are currently loading from lfasiallc.com.  All image paths should be relative etc.  #397 should also help with apica scores.  [See report here](https://wpm.apicasystem.com/BrowserResult/Details?checkId=41407&resultId=39a986b7-ff20-4723-b9c0-b7d573421f46).

- [x] remove flickr images from site and replace with regular gallery
- [x] remove lfasiallc.com requests

**Comment by dankohn** [comment]
I think we will need to disable the Flickr plugin for the China site, based on these latencies:
![image](https://user-images.githubusercontent.com/3083270/71730304-cf911380-2e0f-11ea-9b48-e4caec4b1f76.png)

Instead, I'd recommend that we host the best 10 or 20 images locally and design a custom block showing them off.

**Comment by cjyabraham** [comment]
Weirdly, we also have [this failing local request http://127.0.0.1:11066/getversionjpg?hash=66034](https://tmr.js.org/p/f184df09/) when qq vids try to load but looks like that's an issue with the qq player.

**Comment by cjyabraham** [comment]
I have deployed a change to turn all lfasiallc.com domains to lfasiallc.cn in the content of pages when you are on an lfasiallc.cn page.  We can wait a few days before checking the results in Apica reports.

**Comment by cjyabraham** [comment]
All tasks in this issue are done.  The test results are improved but still have occasional requests that take too long.
