### ISSUE TITLE
Review thumbnail sizes and reduce the list

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#408]
We have 24 image sizes that are generated each time an image is uploaded. It would be good to reduce this list to just those we need.  I think we inherited a lot with FoundationPress and others seem to have come from block plugins.  When we install shortpixel it costs a credit to compress each size so if we don't need all of them we should eliminate some.  [Here is the full list](https://docs.google.com/spreadsheets/d/16hhUCe-CbgyCAlule5DEaim5_IEjTEopwkIccSn4tK0/edit?usp=sharing).  Please comment/edit the sheet so we can decide what to do.

**Comment by thetwopct** [comment]
I added the following to help with the srcset scaling

fp-small (640px × *)
fp-medium (1024px × *)
fp-large (1200px × *)
fp-xlarge (1920px × *)
profile-120 (120px × 120px)
profile-200 (200px × 200px)

I don't remember adding the following and it doesn't seem like its a needed size:

venue (600px × 600px)

I think you can deactivate these unless stackable/UB references them directly by name:
stackable-landscape-large (1200px × 800px)
stackable-square-large (1200px × 1200px)
stackable-portrait-large (1200px × 1800px)
stackable-landscape (600px × 400px)
stackable-portrait (600px × 900px)
stackable-square (600px × 600px)
ub-block-post-grid-landscape (600px × 400px)

This may be from Imsanity, or it could be the new WP image size restrictions, need to check up on that:
1536x1536 (1536px × 1536px)
2048x2048 (2048px × 2048px)

**Comment by cjyabraham** [comment]
I've dug a bit more into this and produced [this sheet](https://docs.google.com/spreadsheets/d/16hhUCe-CbgyCAlule5DEaim5_IEjTEopwkIccSn4tK0/edit#gid=0).  @thetwopct can you take another look at this because what you say above doesn't agree with what I found in the code.  Here is [the key changeset](https://github.com/LF-Engineering/lfevents/commit/9217ae902f8a52401af334b8f10799a7135e1496#diff-84b3fc041db306ebc075fabc23b86b1c) that you made.  Please make some suggestions and then @andycochran and I will take it from there.

**Comment by thetwopct** [comment]
Sorry for my confusion, weirdly I've used fp-small, fp-large etc as thumbnail references on another project (which wasn't FoundationPress).

- profile-120 (120px × 120px)
- profile-200 (200px × 200px)

These aren't currently being used. But at least one probably should be. The speakers images are being loaded at full size in to the page as CSS background images, which means no src set is applied. i.e. Speakers section here: https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/
This image is being loaded - https://events.linuxfoundation.org/wp-content/uploads/profile-18-personal-crop-10MB-scaled.jpg - 845kb for 1 speaker image. ShortPixel AI would solve this, but as we're using IO, WP needs src set to load the correct size image for the user.
To tighten up the number of thumbnails, remove profile-120, profile-200 at 200px is good enough, or remove both if the code won't be fixed.

- venue (600px × 600px)

On the same page reference above, the venue size thumbnail is being used - 600px.
You can remove this, and it will use the 640px size that is also generated (fp-small). Lightspeed won't love it, but for performance and the user it will be fast enough. 

- featured-small (640px × 200px)
- featured-medium (1280px × 400px)
- featured-large (1440px × 400px)
- featured-xlarge (1920px × 400px)

I can't see any of the FoundationPress | featured image sizes being referenced in the code. I think these would typically be used as featured image in blog posts but the posts don't display featured images, and these sizes aren't used in events.

**Comment by cjyabraham** [comment]
Thanks @thetwopct , this really hits home the need to rewrite the speakers block to use srcset.  I've created an issue #419.  I've updated my sheet with [proposed actions](https://docs.google.com/spreadsheets/d/16hhUCe-CbgyCAlule5DEaim5_IEjTEopwkIccSn4tK0/edit#gid=0) to close out this issue.

**Comment by cjyabraham** [comment]
done
