### ISSUE TITLE
Countdown block refactor

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#413]
We use the countdown block on [various event sites](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/).  It comes from the [ultimate block plugin](https://ultimateblocks.com/).  The only reason we use this plugin is to get that block so we carry the weight of the whole plugin in order to use that block.  Could you do the following:

1. Extract the countdown block from the ultimate block plugin so we can use it by itself without the plugin
2. Make the "Weeks", "Days", etc. labels editable so that we can insert Chinese translations on the lfasiallc site

Please do this on a branch in this repo and follow [the instructions here](https://github.com/LF-Engineering/lfevents#lfevents-developer-instructions) including complying with [code sniffs](https://github.com/LF-Engineering/lfevents#code-sniffs).

**Comment by cjyabraham** [comment]
For my own reference, translations to use are as follows:
Weeks 周
Days 日
Hours 小时
Minutes 分钟
Seconds 秒

**Comment by dankohn** [comment]
But please do Chinese then English.

**Comment by rodmeurer** [comment]
Done @cjyabraham 

https://github.com/LF-Engineering/lfevents/pull/417

![image](https://user-images.githubusercontent.com/54405402/72472495-6e7c1f00-37c3-11ea-8072-07f24e6d1b5b.png)

**Comment by cjyabraham** [comment]
Thanks.  In my description I asked that you do this:

> Please do this on a branch in this repo and follow [the instructions here](https://github.com/LF-Engineering/lfevents#lfevents-developer-instructions) including complying with [code sniffs](https://github.com/LF-Engineering/lfevents#code-sniffs).

The advantage of doing it that way is that a dev instance will be automatically created so I can go in and test without having to set it up all locally.  If someone needs adding as a contributor to this repo in order to do that, please let me know.

**Comment by rodmeurer** [comment]
Hi @cjyabraham 

we need access to 
https://github.com/daniloalvess
https://github.com/fuerzastudio

**Comment by cjyabraham** [comment]
Ok, I've added you.

**Comment by rodmeurer** [comment]
Done @cjyabraham 
https://github.com/LF-Engineering/lfevents/tree/fz-413

**Comment by cjyabraham** [comment]
Looks good.  I'll need to coordinate this deployment with the editors.

**Comment by cjyabraham** [comment]
I found an issue with this.  When the block plugin is activated, [the css](https://dev-lfeventsci.pantheonsite.io/wp-content/plugins/countdown-block/dist/blocks.style.build.css?ver=1579251432) affects other aspects of the page.  See how [this page on the dev site looks with the plugin activated](https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-europe/) compared with [the live site without the plugin](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/).  Maybe this needs to be namespaced better?

**Comment by rodmeurer** [comment]
@cjyabraham 

We couldn't see differences between the two pages. We noticed that the plugin that is active in this environment https://dev-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-europe/ is the ultimate-blocks and not the plugin we made.

Can you check and disable ultimate-blocks and enable the countdown-block we made so we can try to see the changes?

**Comment by cjyabraham** [comment]
Sorry.  I had changed the dev environment after writing that comment.

When you activate your plugin it changes at least 3 other parts of the kubecon homepages.  Compare the following 3 images to what you see on [the live site](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/):
<img width="1369" alt="Screen Shot 2020-01-17 at 9 49 38 PM" src="https://user-images.githubusercontent.com/463160/72621190-5e0aa680-3973-11ea-895f-3541b7d4daba.png">
<img width="1331" alt="Screen Shot 2020-01-17 at 9 49 33 PM" src="https://user-images.githubusercontent.com/463160/72621191-5ea33d00-3973-11ea-81cc-590275cf454b.png">
<img width="1338" alt="Screen Shot 2020-01-17 at 9 49 28 PM" src="https://user-images.githubusercontent.com/463160/72621192-5f3bd380-3973-11ea-8004-a7a14d40b6bd.png">

**Comment by rodmeurer** [comment]
Fixed @cjyabraham !

**Comment by cjyabraham** [comment]
Looks good.  Thanks.

**Comment by cjyabraham** [comment]
deployed and [Chinese language added](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/).
