### ISSUE TITLE
Add calendar picker for all dates

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#415]
Date entry locations:
- [ ] Event details
- [ ] Pricing block
...?

**Comment by vibhuti019** [comment]
Hello, I am a newbie and I would like to help out.

**Comment by dankohn** [comment]
Thanks for the interest. This site isn't the best for accepting contributors from new coders. I'd encourage you to consider contributing to some of CNCF's hosted projects: https://github.com/cncf/contribute

**Comment by ANKITSINGH065** [comment]
Can you please shear the file link where we add calendar picker @cjyabraham

**Comment by ANKITSINGH065** [comment]
![change](https://github.com/LF-Engineering/lfevents/assets/101990975/35be9774-8950-4310-bf5a-3af06551c184)

is calendar picker add  here ?
@cjyabraham

**Comment by cjyabraham** [comment]
No. It's for adding the date in the admin for those CPTs.

**Comment by cjyabraham** [comment]
I see no reason to pursue this and add complexity where the current interface is adequate and simpler.
