### ISSUE TITLE
Refresh speaker list in the speakers block when new speaker gets added

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#416]
When I add a new speaker and then open a post with an existing speakers block, the new speaker doesn't show in the drop-down list.  I have to do a hard-refresh in order to see it.  Is it possible to have the speaker show immediately without a hard-refresh?  This is a common use-case for our editors.

**Comment by rodmeurer** [comment]
Done @cjyabraham 
https://github.com/LF-Engineering/lfevents/tree/fz-416

**Comment by cjyabraham** [comment]
Great, nice work!  Deployed.
