### ISSUE TITLE
Text on image block is failing in editor

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#423]
Figure out why the text-on-image block is not rendering in the editor.  I think this is a new problem.  See the [editor here](https://events.linuxfoundation.org/wp/wp-admin/post.php?post=817&action=edit):
<img width="1129" alt="Screen Shot 2020-01-17 at 5 26 28 PM" src="https://user-images.githubusercontent.com/463160/72605062-a6fc3400-394e-11ea-9123-ae20344661b8.png">

To reproduce locally:

1. Create a new Event page and add a text on image block
2. Fill out the image and text
3. Publish the page
4. Hard-refresh the edit screen and you'll see the block saying "This block has encountered an error..."

Dev tools shows this:
<img width="939" alt="Screen Shot 2020-01-17 at 5 32 30 PM" src="https://user-images.githubusercontent.com/463160/72605458-6224cd00-394f-11ea-86a0-c3a2acb0aa75.png">

**Comment by rodmeurer** [comment]
@cjyabraham we made some tests but we couldn't reproduce the error:

https://www.loom.com/share/6f52eef1d8994e79b05142ebba2cf76e

**Comment by cjyabraham** [comment]
Do you have the Gutenberg plugin activated?  My guess is you don't, because mine is fine too when it's not activated.  I suspect this broke during a recent upgrade of the Gutenberg plugin.  I suggest we just leave it for now and hope a later version will resolve the issue.  If not, then we can take a closer look.

**Comment by cjyabraham** [comment]
I've just upgraded to Gutenberg 7.3.0 and it's still an issue.

**Comment by cjyabraham** [comment]
I'm going to close this issue for now since we're not going to run the Gutenberg plugin anymore on the sites but just stay on the version of Gutenberg that comes packaged with WP.  This issue isn't active in that version.
