### ISSUE TITLE
External link icon is wrapping on to a new line

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#426]
Is there a way to keep it stuck to the last word so it doesn't wrap without the word?
<img width="340" alt="Screen Shot 2020-01-20 at 12 12 08 PM" src="https://user-images.githubusercontent.com/463160/72700352-3d626c80-3b7e-11ea-8e0c-d25c0f353c81.png">

**Comment by andycochran** [comment]
I can fix this by adding `margin-right:-1em` to the icon.
