### ISSUE TITLE
Speakers block; make bio start below the photo

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#428]
Currently the bio of a speaker only fills a narrow column:
![image (1)](https://user-images.githubusercontent.com/463160/72773731-a0193e00-3c3a-11ea-94e8-9323befbd363.png)

Make the bio start below the photo and fill the whole column.

**Comment by rodmeurer** [comment]
@cjyabraham done in branch #419 
https://github.com/LF-Engineering/lfevents/commits/fz-419

**Comment by dankohn** [comment]
This preview didn't build. You can see the error by going to slack.cncf.io and looking at #wordpress-logs. 

Here's where the error links: https://circleci.com/gh/LF-Engineering/lfevents/5548?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack

**Comment by fuerzastudio** [comment]
@dankohn I believe this failure did not originate in this commit, as you can see at the followed links:
https://circleci.com/gh/LF-Engineering/lfevents
https://circleci.com/gh/LF-Engineering/lfevents/5531

But I'll talk with @cjyabraham and investigate a little deeper what is causing that, thanks for warning us

**Comment by cjyabraham** [comment]
Ok.  Can you make it so that just the bio text is below the image but keep the name, title, and any social links to the right of the speaker image?  I've filled out some bios and social links [here](https://pr-425-lfeventsci.pantheonsite.io/open-networking-edge-summit-north-america/program/program-committee/) so that we can test this adequately.

BTW, it looks like the PR instance did get created but just that the wraith visual regression tests failed because the PR instance is now out of sync with the DB of the live instance.

**Comment by rodmeurer** [comment]
@cjyabraham up-to-date!

**Comment by cjyabraham** [comment]
@dankohn @andycochran any thoughts on the [new bios layout](https://pr-425-lfeventsci.pantheonsite.io/open-networking-edge-summit-north-america/program/program-committee/)?  I think the spacing between the social links and the top of the bios could be reduced by half, but otherwise, looking good!

**Comment by dankohn** [comment]
Agreed.

**Comment by cjyabraham** [comment]
@rodmeurer can you make the spacing change?  (it seems like there's an extra `<p>` in the markup)

**Comment by cjyabraham** [comment]
I've made the change needed to remove the space and deployed the update.  [Here it is live](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/).
