### ISSUE TITLE
Countdown mobile render issue

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#431]
Can you try and fix the mobile render issue with the numbers being too high?  Can you get it to look like the desktop view?

<img width="391" alt="Screen Shot 2020-01-22 at 10 16 59 AM" src="https://user-images.githubusercontent.com/463160/72862602-57c45380-3d00-11ea-9d55-3be886fb645c.png">

**Comment by rodmeurer** [comment]
Fixed @cjyabraham 
https://github.com/LF-Engineering/lfevents/commits/fz-431

![image](https://user-images.githubusercontent.com/54405402/72920002-31fe7500-3d27-11ea-85c4-e354ceb7eb91.png)

**Comment by cjyabraham** [comment]
Great!  Deployed.
