### ISSUE TITLE
Modernize deployment process

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#434]
Avoid having to use the Pantheon dashboard to do deployments.  As per @dankohn, create a separate production branch in which any pushes would automatically perform the deployment. Have an alias to push master to production: 
`alias production='git checkout production; git pull; git merge --ff-only origin/master; git push; git checkout master' # push master to production`

Have CircleCI clear both the Pantheon and Alibaba caches.

Use [these](https://www.alibabacloud.com/help/faq-detail/40188.htm) [resources](https://partners-intl.aliyun.com/help/doc-detail/123574.htm) [to automate](https://www.alibabacloud.com/help/doc-detail/27140.htm) the Alibaba refresh.

First step is to talk with Pantheon wrt whether this is possible.

**Comment by dankohn** [comment]
It looks like you can use the `only: production` branches feature of `circle.yml` to execute Terminus commands to deploy to production and clear the cache. You would want to confirm best practices with Pantheon first.

https://circleci.com/docs/2.0/deployment-integrations/
https://pantheon.io/docs/guides/terminus-drupal-site-management/

**Comment by cjyabraham** [comment]
[Pantheon Quicksilver](https://pantheon.io/docs/guides/edt/external-integrations) can be used to automate the Alibaba CDN cache clear when the Pantheon cache is cleared.

**Comment by cjyabraham** [comment]
I see no reason to pursue this now as we are comfortable with our current process.
