### ISSUE TITLE
Re-architect sponsors block and migrate all sponsors over

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#435]
The sponsors block currently stuffs the logo url and forwarding url directly in the content of posts.  Since this url and logo gets updated frequently, we need a more effective method for updating these across all Event sites at once.

We should re-architect sponsors to be a CPT that then are loaded dynamically from the server to populate posts, similar to how speakers is done.  Here is what needs to happen:

- [x] Create sponsor CPT.  The logo will be its Featured Image.  There will be a meta box for the forwarding url.  
- [x] write migration 
- [x] Create new sponsor block which will do a dynamic lookup similar to how the speakers block works.  The html will be generated on the server and will match the existing html when inserted into post content.
- [x] Deploy live so that both sponsor blocks can live side-by-side without conflicting 
- [x] Run migration by creating a "migrate-sponsorss" Event and then opening in a browser, then change the slug to "migrate-sponsors" in the admin and refresh Event; delete this Event after running 
- [x] Transform each existing sponsor block into a new sponsor block on each Event (Chris and Megan)
- [x] Update [Admin Instructions](https://docs.google.com/document/d/1mvIuw-R9k_gbnZn_iV04qNTjG33u_lXwFlN7s-lgJ1Y/edit#heading=h.d9qyzr39i0a3)
- [x] Uninstall old sponsor block
- [x] Uninstall Media Categories plugin which is now no longer needed
- [ ] Set media files to now be stored in dated directories (we had them storing all in one directory to facilitate the old way of swapping sponsor logos); this needs testing to make sure we can just switch over
- [x] Remove [old code used to update cache](https://github.com/LF-Engineering/lfevents/commit/c8089cddda14b88c950405b9dde82298f0ee47ed) if we no longer need it
- [x] Remove [code used to migrate sponsors](https://github.com/LF-Engineering/lfevents/commit/88b345f9779c034b02ffd98521f19029785416f5)
- [x] Relabel "Sponsors Dynamic" block to just "Sponsors"

The editors are fine choosing sponsors from a text-only box like we have in the speakers block.  They will differentiate between different company logos in the title of the logos.

Megan is willing to help me with any migration steps but is not much available Feb 3-7.

**Comment by dankohn** [comment]
I suspect you'll want to find a programmatic way to "Migrate all sponsor
logos into the CPT".

>

**Comment by cjyabraham** [comment]
_Can I keep using the Media Library rather than create a new CPT???_ This needs testing out as it would save us having to do one migration.  We can fall back to CPT if it doesn't work.

**Comment by cjyabraham** [comment]
I split out the last task as #454
