### ISSUE TITLE
Add link on old kubecon site homepage to point to current kubecon site

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#437]
To help with SEO and also to help visitors who end up on an old site by accident, create a prominent link in the hero of the old sites with the words: "This event has passed.  Go to the current KubeCon + CloudNativeCon North America [Europe or China] site."  Link the words "KubeCon + CloudNativeCon North America".  

Do it for the following sites:
- https://events19.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/
- https://events19.linuxfoundation.cn/events/kubecon-cloudnativecon-china-2019/
- https://events19.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2019/
- https://events19.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2018/
- https://events19.linuxfoundation.cn/events/kubecon-cloudnativecon-china-2018/
- https://events19.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2018/

**Comment by dankohn** [comment]
Great, but it's `KubeCon + CloudNativeCon`

**Comment by alexcontini** [comment]
these are now all updated, let me know it there are any issues!

**Comment by cjyabraham** [comment]
@alexcontini Can you link all these words “KubeCon + CloudNativeCon North America” for each of them?

**Comment by alexcontini** [comment]
@cjyabraham sorry about that, not sure why I linked all words for only the first one. All the updates are now made!

**Comment by cjyabraham** [comment]
Looks great.  Thanks.
