### ISSUE TITLE
Text-on-image block srcset/admin refactor

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#440]
Get the text-on-image block to insert the image via srcset so that it performs better on mobile.  Also, make the admin ui more user-friendly.  Right now it's sometimes not obvious that you can enter text.

**Comment by cjyabraham** [comment]
Can you address #423 at the same time please?

**Comment by rodmeurer** [comment]
Done @cjyabraham 

Basically, it will be necessary to remove the old blocks and add them again, as the markup and also the way to save has been changed.

We did it at this event: https://pr-446-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

**Comment by cjyabraham** [comment]
Thanks.  Admin looks good.  Can you get it to work responsively like the current version.  See how [this one](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/) responds to narrow browser widths:
<img width="501" alt="Screen Shot 2020-01-29 at 4 18 17 PM" src="https://user-images.githubusercontent.com/463160/73343318-fcbbcf00-42b2-11ea-9683-d7689fe427f5.png">

**Comment by rodmeurer** [comment]
@cjyabraham fixed.

**Comment by cjyabraham** [comment]
Can you make it so that it covers less of the photo?  See above photo vs yours below:
<img width="499" alt="Screen Shot 2020-01-30 at 2 59 46 PM" src="https://user-images.githubusercontent.com/463160/73430678-3d7a1d80-4371-11ea-8efe-a94f80626356.png">

We did this deliberately because often we put photos there that we don't want to cover up.  If you could try and match the design of the existing version as much as possible it would be good.

**Comment by rodmeurer** [comment]
Fixed @cjyabraham, let us know if it's ok now.
https://pr-446-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

**Comment by cjyabraham** [comment]
Looks good.  Thanks.

**Comment by cjyabraham** [comment]
Reassigning to myself to deploy and migrate over existing blocks.

**Comment by cjyabraham** [comment]
@rodmeurer I've merged this but am now seeing that there's still a [background-image being set on the container element](https://github.com/LF-Engineering/lfevents/commit/95f417390346578fc86fcb61f0e1dab0ee01c7dc#diff-6150e76be4b10d11340c9bd60ada96bdR96) even though you're dropping the image in with an `<img>` tag.  This is now causing, in some cases, two sizes of the same image to download for the block, such as when you have a mobile-width viewport.  Can you take a closer look at this please?  You can [see it live here](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/).  And here is what I'm seeing in dev tools when I have a mobile width:
<img width="1026" alt="Screen Shot 2020-02-01 at 6 12 15 PM" src="https://user-images.githubusercontent.com/463160/73591211-668be100-451e-11ea-90bf-9a6090607796.png">

**Comment by rodmeurer** [comment]
@cjyabraham we removed the background image that was causing this and now it loads only one image.

https://pr-464-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

**Comment by cjyabraham** [comment]
Thanks.  Deployed.
