### ISSUE TITLE
Hide RECAPTCHA badge on forms

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#441]
Include [text](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed) instead in the footer.

**Comment by cjyabraham** [comment]
Done.  @dankohn please LMK if [the footer text](https://events.linuxfoundation.org/) is not ok.

**Comment by dankohn** [comment]
LGTM
