### ISSUE TITLE
Provide styles for our update to the homepage filters

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#442]
Can you give me the styles so that this can be implemented:
![image](https://user-images.githubusercontent.com/463160/73115019-e5977d00-3f52-11ea-813a-dd109b82a3f8.png)

**Comment by andycochran** [comment]
Just pushed changes to `master` that handle these styles. I pulled staging content to confirm. You'll just need to make sure that the field has the same data attribute in prod (`[data-sf-field-name="search"]`) and change the placeholder text to say "Filter by event, location, topic…"

**Comment by cjyabraham** [comment]
deployed
