### ISSUE TITLE
Sponsor Dynamic block tweaks

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#444]
I have refactored the Sponsor block and called it the "Sponsor Dynamic" block.  It now works similar to the Speakers block that @fuerzastudio worked on.  Could I get some help from @fuerzastudio to tweak the new Sponsor Dynamic block.  Specifically, instead of allowing a user to re-order the list, as in Speakers, the order should always be alphabetical.  Can we enforce that within the admin UI for the block?  Feel free to use a different control if it would suit the use-case better.

Please work directly on the [sponsors-refactor branch](https://github.com/LF-Engineering/lfevents/tree/sponsors-refactor).  [Here is a working instance](https://pr-443-lfeventsci.pantheonsite.io/).

<img width="762" alt="Screen Shot 2020-01-26 at 6 49 13 PM" src="https://user-images.githubusercontent.com/463160/73134730-92195200-406c-11ea-8381-40f9c3f7f997.png">

**Comment by rodmeurer** [comment]
Done @cjyabraham

**Comment by cjyabraham** [comment]
Looks good.  Thanks.
