### ISSUE TITLE
Add padding to topnav SVG logo

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#449]
Megan is currently using two different svg event logos, one for the hero image and one for the top-left topnav logo.  The hero image needs no padding around it but for the topnav one they always want about 8-10 pixel padding around it or else it looks too big.  Can we allow them to use the no-padding svg in both places and have the padding added to the styles of the topnav instead?  This way Creative Services would only have to create one svg per event instead of two.  

Do this in a branch so that we can merge when Megan is ready to do the migration for each of the existing events.

**Comment by dankohn** [comment]
Note that we will probably soon be running all SVGs through autocrop.cncf.io which adds 1 pixel of transparent border around an SVG. 

Hopefully, you can use CSS to add more.

**Comment by cjyabraham** [comment]
I need to discuss this with Megan prior to deploying.  It is in this [PR](https://github.com/LF-Engineering/lfevents/pull/467).  It appears that only the [LF Energy](https://events.linuxfoundation.org/lf-energy-open-source-bootcamp/) logo has been manually padded.  On deployment, this logo will need to be switched for the unpadded version.

**Comment by cjyabraham** [comment]
This is deployed with the [LF Energy](https://events.linuxfoundation.org/lf-energy-open-source-bootcamp/) and [Prestocon](https://events.linuxfoundation.org/prestocon/) logos migrated to their unpadded versions.
