### ISSUE TITLE
Cacheing issue with sponsor and speakers block lookups

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#451]
The new Sponsors Dynamic block and Speakers block appear to cache the suggestion lookup queries somewhere.  To test, follow these steps:

1. Create a new sponsor block
2. Test for a sponsor that doesn't exist, like "qwerty", by typing one letter at once ("q", "qw", "qwe"...) and having the sponsor block try to find the sponsor each time.
3. Add a sponsor called "qwerty" in a new tab
4. Back in the original tab, try searching again for "qwerty" using any number of letters ("q", "qw", "qwe"...) and you will see that it won't find it.
5. Try searching for "wert", or any letter combination which had previously not been searched for, and you'll see that it finds it because that query hadn't been cached anywhere.

This issues seems to be with browser cache, because it you go into an incognito tab you'll be able to search for "qwerty" successfully.  Is it possible to keep this browser cache cleared so that new sponsors can immediately be searched for?

All of the above applies to the Speakers block as well.

**Comment by rodmeurer** [comment]
@cjyabraham 

We did some tests here and this problem doesn’t happen in the local environment. In the testing environment (https://dev-lfeventsci.pantheonsite.io) we managed to reproduce.
There is no cache being done in the browser. With each search, a new request is made for a route in the WordPress REST API. So, we noticed that in the testing environment it sometimes did not return results, even though we registered a speaker. We think it might be some kind of cache at the server side.

To try to get around this situation, we added a parameter with a timestamp in requests. We did a few more tests and we believe it solved the problem.

Below is a video with the tests:
https://www.loom.com/share/2961ae42372941d696e1094cee43e4cf

PR: https://github.com/LF-Engineering/lfevents/pull/453

**Comment by dankohn** [comment]
I just wanted to mention that adding a cache-busting date and time to the API call was very clever.

**Comment by cjyabraham** [comment]
Works great.  Thanks.

**Comment by cjyabraham** [comment]
It looks like Pantheon caches the REST API quite aggressively.  I was doing some research on this today. 
 In the future, we can explicitly omit our REST paths from the cache using [this approach](https://pantheon.io/docs/mu-plugin#wp-rest-api-code-classlanguage-textwp-jsoncode-endpoints-cache).

**Comment by cjyabraham** [comment]
@rodmeurer now that we've found this new way of dealing with the cached REST APIs, could you revert the work you've done here with adding a timestamp and add the REST API paths to [this code here](https://github.com/LF-Engineering/lfevents/commit/8500dc28ca07de320becd3d432e76aa1705ab6c0).  It'd be good to handle this issue consistently across our code.

**Comment by cjyabraham** [comment]
Thanks.  Deployed.
