### ISSUE TITLE
Fix security alerts on lfevents and cncfci repos

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#456]
[LFEvents alerts](https://github.com/LF-Engineering/lfevents/network/alerts)
[CNCFCI alerts](https://github.com/cncf/cncf.io/network/alerts)

Use the [npm-shrinkwrap](https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions/17423915#17423915) approach.

**Comment by cjyabraham** [comment]
I've overridden the dependency in the package-lock file for mem.  New installs should use the `[npm ci](https://docs.npmjs.com/cli/ci.html)` command instead of `npm install` as it won't recalculate and write to the package-lock files.  It simply takes what's defined in the package-lock file and installs it.  New devs should always be running `npm ci`.

The [npm-shrinkwrap approach](https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions/17423915#17423915) wasn't appropriate here.  It too gets overridden if someone were to run `npm install` so has the same problem as the package-lock file.

**Comment by cjyabraham** [comment]
[Also fixed on the cncfci repo](https://github.com/cncf/cncf.io/commit/b86cfe3bc92245081087fbb01fd633991227d526)

**Comment by dankohn** [comment]
I think you want to update https://github.com/LF-Engineering/lfevents/blob/master/docs/devguide.md with a clear warning to use `npm ci` not `npm install`.

**Comment by cjyabraham** [comment]
Good idea.  [Done](https://github.com/LF-Engineering/lfevents/blob/master/docs/devguide.md#lando-setup).
