### ISSUE TITLE
Make KCD imported community events immediately publish

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#461]
We need to get the country code mapped first.  @dankohn has exposed a [2-letter country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) in [the feed](https://deploy-preview-274--kubernetes-community-days.netlify.com/index.xml) for me to translate.

**Comment by dankohn** [comment]
Working: https://kubernetescommunitydays.org/index.xml

**Comment by cjyabraham** [comment]
@dankohn how likely is it that a KCD will be created in a country for which we currently don't have any events?  Currently we use the same [Country taxonomy](https://events.linuxfoundation.org/wp/wp-admin/edit-tags.php?taxonomy=lfevent-country&post_type=lfe_community_event) we use for main Events when categorizing Community Events.  And that list is hierarchical.  I'm trying to figure out what to do when a KCD arrives for which there is not already a country in the Country taxonomy.  There are a few options:
1. Create a new non-hierarchical Country taxonomy just for Community Events which we can automatically add to if there is no matching entry already for a country.  Since it's non-hierarchical we won't need to worry about correctly matching a continent.  This can also be more easily leveraged by the [Community Event suggestion form](https://events.linuxfoundation.org/about/community/) which currently relies on an admin assigning the correct country.
2. Keep using the existing Country taxonomy but, when there is no matching country, keep the incoming KCD in draft mode so that it can be manually assigned.  Maybe we can shoot of an email notification to have someone assign it.  This has the advantage of keeping the Country filter UI consistent across the site.
3. Scrap using a Country taxonomy entirely and just use a Country text field (which won't be filterable) for each Community Event.  This is easiest to implement but we'd lose the filter.
4. Populate the [full list of Countries](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) in the current taxonomy now so that a matching country will always be available.  This can also be leveraged by the [Community Event suggestion form](https://events.linuxfoundation.org/about/community/).

Having written out this list, it seems that 4 is the best option, though there's a lot of data entry that will be needed.  Any objections or additional ideas?

**Comment by dankohn** [comment]
It's certain. Let's go with 4, please.

**Comment by cjyabraham** [comment]
@dankohn is there an official list of continents and countries we should use?  I've found two options:
1. [datahub](https://datahub.io/JohnSnowLabs/country-and-continent-codes-list#data-cli)
2. [wikipedia](https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_by_continent_(data_file))

I assume we'll keep the current names that are in the db which won't exactly match this list.  For example, we have "United States" instead of "United States of America".

**Comment by dankohn** [comment]
Let's please use the same list as the visa form. You'll need to map the two
letter codes to it.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by cjyabraham** [comment]
A few outlier questions:
1. Should we go with Russia or Russian Federation?
2. Should we go with both Asia and Oceana or just Asia Pacific?
3. Should we go with "Korea, Democratic People's Republic of" or "South Korea"?

**Comment by dankohn** [comment]
Russian Federation. South Korea. No Oceania, please, because not enough
people are familiar with it.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by cjyabraham** [comment]
Did you see question 4: What should we do with countries that belong to two continents, like Russia? WordPress hierarchical taxonomies can only have one parent.

**Comment by cjyabraham** [comment]
I've split off [a separate issue](https://github.com/LF-Engineering/lfevents/issues/470) for Diego's team to write the import.

**Comment by dankohn** [comment]
Please put Russian Federation, Cyprus, Turkey in Europe and Armenia, Azerbaijan, and Kazahkstan in Asia.

**Comment by cjyabraham** [comment]
The countries are now imported.  What's left is to match the incoming KCD events to the correct country.

**Comment by cjyabraham** [comment]
@dankohn the [KCD feed](https://kubernetescommunitydays.org/index.xml) now seems to use just the city for the title.  Is this a permanent change?  If so I’ll need to know to prefix that with “Kubernetes Community Days”?

**Comment by cjyabraham** [comment]
This is built and deployed but posts are still being imported as "Draft" until we get a resolution to the question to @dankohn above.

**Comment by dankohn** [comment]
Yes, the field in the KCD form is `city` so please prepend `Kubernetes Community Day `.

E.g.: https://github.com/cncf/kubernetes-community-days/blob/master/content/events/2020-london/_index.md

**Comment by dankohn** [comment]
Once the KCDs are populating, please also ask Marisa to delete SUSEcon, Red Hat Summit, Google Next, and Microsoft Build since they don't follow the [policy](https://events.linuxfoundation.org/about/community/) of not listing for-profit events.

**Comment by cjyabraham** [comment]
KCD events are now [immediately publishing](https://events.linuxfoundation.org/about/community/?_sf_s=kubernetes).

**Comment by cjyabraham** [comment]
done.
