### ISSUE TITLE
Hide countdown clock from Google snippets

### ISSUE THREAD

**Issue by dankohn** [LF-Engineering/lfevents#469]
![image](https://user-images.githubusercontent.com/3083270/74094138-605fac80-4aaa-11ea-8b02-ebb11dc1850d.png)

**Comment by cjyabraham** [comment]
Can you re-upload the image?  It seems broken.  I tried Googling for "kubecon Amsterdam" but can't find anything with the countdown clock text...

**Comment by rodmeurer** [comment]
We checked the content displayed by the meta-description tag and it's OK. The "countdown" block information does not appear. So, We added an attribute to ignore the block markup in Google search results.

References:
https://support.google.com/webmasters/answer/79812#data-nosnippet
https://support.google.com/webmasters/answer/6229325

PR: https://github.com/LF-Engineering/lfevents/pull/472
environment: https://pr-472-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-europe/

**Comment by cjyabraham** [comment]
Thanks.  This is deployed.
