### ISSUE TITLE
Import all countries into lfevent-country taxonomy

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#470]
We want to import [this list of countries](https://docs.google.com/spreadsheets/d/1MNZPyyQmDsMOj6SVlwecW7nj_2ytveTQGdFtruYb6GQ/edit?usp=sharing) into our Countries Taxonomy (lfevent-country) on the main event site.  We'll run it on the live site and then delete the code.

The import should work like this:
1. Step through existing entries in the lfevent-country taxonomy.  Change all slugs to the Two_Letter_Country_Code or Continent_Code_edited as appropriate.  All existing entries should match on either the Continent_Name_edited or Country_Name_edited columns.
2. Step through all countries in the spreadsheet and perform the following: if the country already exists, move on to the next one.  If it doesn't exist, insert it and set its parent continent and slug (Two_Letter_Country_Code) appropriately.  If the country appears twice in the spreadsheet with two different continents, only use the first one you come across.

**Comment by rodmeurer** [comment]
@cjyabraham 

We implemented an import script that must be executed through the fz-countries parameter in any area of administration.

It must be performed in the following order:

1 - wp-admin/?fz-countries=update;
2 - wp-admin/?fz-countries=import

The first to update the existing terms and the second to import the new terms from the spreadsheet.

We've already run in this environment: https://pr-473-lfeventsci.pantheonsite.io/wp/wp-admin/edit-tags.php?taxonomy=lfevent-country&post_type=page

PR: https://github.com/LF-Engineering/lfevents/pull/473

**Comment by cjyabraham** [comment]
Thanks.  I've run the import on the live server and then reverted the commit to keep the code clean.
