### ISSUE TITLE
Improve validation for forms

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#474]
The [visa request form](https://events.linuxfoundation.org/about/visa-request/) allows a user to enter hello@emailcom for an email address and also characters like "-" and "." in the date field.  Make the field validation more restrictive to only allow valid entries.

**Comment by vibhuti019** [comment]
hello I am a newbie and I would like to help out.

**Comment by cjyabraham** [comment]
WRT email format, [not having a dot in the domain part is actually valid](https://en.wikipedia.org/wiki/Email_address#Syntax).

**Comment by vibhuti019** [comment]
I will work on this issue.

**Comment by cjyabraham** [comment]
Thanks @vibhuti019 but we're not really looking for contributors on this repo.

**Comment by cjyabraham** [comment]
Date fields updated throughout all visa request and travel fund forms.
