### ISSUE TITLE
Use dates to control CTA buttons on homepage

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#478]
Create date fields to control the CTA buttons that appear on the [homepage](https://events.linuxfoundation.org/).  Megan has approved this change. 
- Current CFP dates will control the "Speak" button
- New dates are needed for Register and Sponsor buttons
- Schedule button doesn't need dates

**Comment by cjyabraham** [comment]
@meganelizabethphillips can you double-check how I've described this above and give your approval before I implement?

**Comment by meganelizabethphillips** [comment]
Perfect!

**Comment by cjyabraham** [comment]
@meganelizabethphillips, just wanted to check, should the Register button have its own start and end dates (as described above) or, alternatively, it could be shown as soon as you enter a url and be removed as soon as the start date for the event has passed?

Similarly, should the sponsor button have a start date, or can that just be shown as soon as you enter a url for it?

**Comment by dankohn** [comment]
The register button should disappear as soon as the *end* date has passed, since you can register on the third day of a conference.

**Comment by meganelizabethphillips** [comment]
@cjyabraham the sponsor button doesn't need a start date - I like the URL idea!

**Comment by dankohn** [comment]
The sponsor button can use existence of a URL as the start date but does need an *end* date because sponsorships normally aren't accepted for the month before the event due to printing deadlines.

**Comment by cjyabraham** [comment]
Ok, cool.  So I'll do it like this:
<img width="271" alt="Screen Shot 2020-03-04 at 3 38 29 PM" src="https://user-images.githubusercontent.com/463160/75855933-3f327780-5e2e-11ea-88a1-93f3936bee61.png">

**Comment by cjyabraham** [comment]
This is deployed.  I made the following edits to event info:
- I updated the CFP dates on an AGL conference to match what was on [the CFP page](https://events.linuxfoundation.org/agl-amm-summer/program/cfp/#overview)
- I entered the CFP dates for the gRPC conference to be what was on [the CFP page](https://events.linuxfoundation.org/grpc-conf/program/cfp/#overview)

There were also a couple of Speak buttons that rightfully disappeared from the homepage as their CFP close date had passed.
