### ISSUE TITLE
Illustrations used in Event headers doesn't stretch effectively

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#479]
Some of the headers have illustrations that don't look good as they leave stripes at the top/bottom of them when the header title goes to two lines.  See [this one](https://events.linuxfoundation.org/agl-amm/attend/novel-coronavirus-update/) and [this one](https://events.linuxfoundation.org/continuous-delivery-summit/attend/novel-coronavirus-update/) as examples.  Do we need to modify our recommendation for size in the [Style Guide](https://docs.google.com/document/d/1mvIuw-R9k_gbnZn_iV04qNTjG33u_lXwFlN7s-lgJ1Y/edit#heading=h.eoadtlfn2fih) to account for two-line titles?

<img width="1432" alt="Screen Shot 2020-02-12 at 2 44 12 PM" src="https://user-images.githubusercontent.com/463160/74313392-2fcb8b80-4da6-11ea-9703-c35b526bb4a3.png">

**Comment by andycochran** [comment]
The current method of sizing `figure img` will also show whitespace on the sides on really large screens if the image is too narrow. It seems that the `object-fit: cover` rule doesn't isn't really working. I nixed the explicit widths/heights and added max/mins. That seems to fix it. Putting together a PR…

**Comment by cjyabraham** [comment]
@meganelizabethphillips Andy has updated the [style guide](https://docs.google.com/document/d/1mvIuw-R9k_gbnZn_iV04qNTjG33u_lXwFlN7s-lgJ1Y/edit#heading=h.lbz0zwbo64iu) to recommend taller images (> 2400 x 750 px) for the "Event Featured Image" and has added this comment:

> The Event Featured Image (that’s behind the title of subpages) crops to a fluid landscape ratio — about 3.5:1 for single-line headings and 3:1 when the heading wraps to 2 lines. 

Is that sufficient to help you fix these issues?  Basically you just need taller images but need to be mindful that there's nothing essential at the top that might get cropped for single-line titles.

**Comment by meganelizabethphillips** [comment]
This is perfect @andycochran and @cjyabraham - thank you so much!
