### ISSUE TITLE
&nbsp; cause speakers bios to flow off screen on mobile

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#495]
For some reason this speakers bio text [on this page](https://events.linuxfoundation.org/open-networking-edge-summit-north-america/program/featured-keynote-speakers/) is partially hidden for Alex Choi.  It doesn't seem to be a problem for other speakers.
<img width="383" alt="Screen Shot 2020-02-23 at 2 26 52 PM" src="https://user-images.githubusercontent.com/463160/75105672-d5091e00-5648-11ea-968f-e3cf17c24105.png">

**Comment by andycochran** [comment]
Looks like it's full of non-breaking spaces: 

![image](https://user-images.githubusercontent.com/409279/75510103-ceb3d280-59b7-11ea-9521-680bf5833018.png)

**Comment by andycochran** [comment]
Unrelated to the text overflowing, but another issue with the layout… Why is the speaker block inside another container that adds whitespace around it? That gives the speakers less width than they need.

**Comment by cjyabraham** [comment]
I guess @meganelizabethphillips preferred it that way?

@meganelizabethphillips also FYI, see the above issue with Alex Choi's bio, which I've now fixed.  It looks like Jillian might have copy/pasted it from somewhere with these `&nbsp` chars.

**Comment by meganelizabethphillips** [comment]
@cjyabraham interesting! No clue how that would have happened. I'll let the speaker team know to be mindful when copying/pasting the bios (which is pretty sure how they are doing all of them!). Thanks for bringing this to my attention.

**Comment by andycochran** [comment]
Pasting w/o formatting has kinda become muscle memory for me. Might be worth letting people know about: 

> On Windows, while it’s not universal, many apps support the shortcut Ctrl + Shift + V to paste without formatting. These include Chrome, Firefox, and Evernote.
> 
> To paste as plain text on a Mac, you can use the somewhat cumbersome shortcut Option + Cmd + Shift + V to paste without formatting. This is a system-wide shortcut, so unlike Windows, it should work everywhere.

**Comment by meganelizabethphillips** [comment]
This is great to know - thanks so much Andy! I will share with the team.

Megan Phillips, PMP
Events Web Project Manager
The Linux Foundation
1 Letterman Drive
Building D, Suite D4700
San Francisco, CA 94129
E: mphillips@linuxfoundation.org



Why Attend Linux Foundation Events <https://youtu.be/X_rLxfmLlYY>
Why Sponsor Linux Foundation Events <https://youtu.be/Rr-9cIH42fE>


_______________
*Upcoming Out of Office*
Onsite: Friday, March 6 - Monday, March 9 (delayed email response; no calls)
OOO: Tuesday, March 10 (no access to email/phone)
