### ISSUE TITLE
Use `.callout.alert` for form error message

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#497]
What style should I use for an error message on form submission?  We use the `callout` and `success` classes on successful submission but what should we use on error?

**Comment by andycochran** [comment]
The `.callout` class has other states you can use besides `.success`: 
https://get.foundation/sites/docs/callout.html#coloring

For form errors, I'd suggest using `.alert`, which will tint the `.callout` red.

**Comment by andycochran** [comment]
Is there a certain place you'd like me to implement something? Or were you just looking for my input on this?

**Comment by cjyabraham** [comment]
I think I can take it from here.  It's to style an error message on our forms.  Thanks.
