### ISSUE TITLE
Stop "Timer expired" flash when a countdown block has expired

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#500]
When a countdown block timer has expired, the words "Timer expired" flash on the screen in place of the countdown when the page loads, and then they disappear.  Can you stop this from happening.  See [this sandbox event](https://sandbox-lfeventsci.pantheonsite.io/kubernetes-forum-delhi/) as an example:

<img width="572" alt="Screen Shot 2020-02-27 at 11 19 26 AM" src="https://user-images.githubusercontent.com/463160/75411796-0b011780-5953-11ea-970d-bc858e731b45.png">

**Comment by deigolocco** [comment]
@cjyabraham is done.
Env test: https://pr-502-lfeventsci.pantheonsite.io
PR: https://github.com/LF-Engineering/lfevents/pull/502

**Comment by cjyabraham** [comment]
This looks good.  Thanks.
