### ISSUE TITLE
Turn forms into custom Gutenberg blocks

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#503]
We have a set of [common forms](https://github.com/LF-Engineering/lfevents/blob/master/docs/formcode.md) that we have refined over time.  Currently we have the raw html/js embedded in each Event page.  Any updates and improvements to a form need to be done by hand across all Events. 

They could, instead, be turned into custom Gutenberg blocks.  The editor would just have to set the event ID for each on inserting into a page.  The following forms could be done this way:
- Newsletter
- Visa Request
- Contact Us
- Kubecon Sponsor
- Travel Fund Request
- Livestream Signup form

One huge advantage to doing it this way is that the form code can be built on the server so anytime we need to update it across all events, it can just be updated there once and deployed.  It would also be easier and less error-prone for Megan to insert onto a page.

Create a single plugin that has multiple gutenberg blocks, one for each form.  Each block will need to accept certain meta data from the editor such as event ID or form action url, depending on the form.  Make it simple enough so that I can easily add more forms in the future.

Call the plugin "LFEvents Forms".  Call each Gutenberg block "Newsletter Form", "Visa Request Form" etc.  Please start with just those two forms and we can test it out before doing the other forms.

**Comment by cjyabraham** [comment]
Megan is in favor of this.

**Comment by rodmeurer** [comment]
@cjyabraham it's done.

We created the plugin **LFEvents Forms** and added the two forms as requested (Newsletter Form and Visa Request Form).

PR: https://github.com/LF-Engineering/lfevents/pull/513
Example: https://pr-513-lfeventsci.pantheonsite.io/2020/03/06/forms-example/

**Comment by cjyabraham** [comment]
Great!

Each form includes [sfmc-forms.js](https://github.com/LF-Engineering/lfevents/blob/master/web/wp-content/themes/lfevents/src/assets/js/sfmc-forms.js) which it currently pulls from events.linuxfoundation.org.  I think it makes sense to include that from within the plugin and take it out of the theme.  The plugin could compile that file and enqueue it only when a form is present on the page.  Alternatively, the js could just be dumped inline below each form when you insert on a page.  I'm not sure which would be the best option.  Do you have an opinion?

Could you also include the [livestream form](https://github.com/LF-Engineering/lfevents/blob/master/docs/formcode.md#live-stream)?  Note the livestream form has its own form js handler with the only difference is that it redirects the page after the form successfully submits.  Could you consolidate that js code with [sfmc-forms.js](https://github.com/LF-Engineering/lfevents/blob/master/web/wp-content/themes/lfevents/src/assets/js/sfmc-forms.js) and just have the redirect optional when that parameter is supplied by the block?

Finally, can you group all these form blocks within their own "LFEvents Forms" section in the block picker?

**Comment by rodmeurer** [comment]
@cjyabraham done as you requested.

**Comment by rodmeurer** [comment]
@cjyabraham The sfmc-forms.js script was already embedded in each form. We implemented your first suggestion, to add it only once on the page, whenever one of the form blocks is present.

**Comment by cjyabraham** [comment]
Looks great!

Can you render the forms on the front-end only if all the required parameters have been entered for the block?  The forms will not work unless all parameters are set.

**Comment by rodmeurer** [comment]
@cjyabraham done.

**Comment by cjyabraham** [comment]
This is great and is now deployed.  Thanks!
