### ISSUE TITLE
Set blog post social image to the LFEvent logo

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#507]
@meganelizabethphillips can you confirm what image you'd like for this and I can set it up?

**Comment by meganelizabethphillips** [comment]
@cjyabraham hot off the press from CS! Please find it attached.
![LF_Events_BlogImage-01](https://user-images.githubusercontent.com/47828554/76439387-f294f200-6381-11ea-9eed-5a146b634633.png)

**Comment by cjyabraham** [comment]
@meganelizabethphillips can you confirm, do you want that image to be the fallback image used across the whole site, whenever a specific image isn't provided?  Or do you want it just for the blog posts?  And have [this image](https://events.linuxfoundation.org/wp-content/uploads/cropped-color2.jpg) be the fallback for everything else?

**Comment by cjyabraham** [comment]
Separately, the homepage had [this image set (513px wide)](https://events.linuxfoundation.org/wp-content/uploads/cropped-hp1-1.jpg) as the social image.  I have updated it to be [this larger version (1075px wide)](https://events.linuxfoundation.org/wp-content/uploads/2019/09/welcome.jpg).

The SEO plugin recommend a social image with dimensions of at least 1200 x 630 px to work in the various places it is used.  I have updated the [Style Guide](https://docs.google.com/document/d/1mvIuw-R9k_gbnZn_iV04qNTjG33u_lXwFlN7s-lgJ1Y/edit#heading=h.lbz0zwbo64iu) with this info.

**Comment by meganelizabethphillips** [comment]
@cjyabraham  I think it should be the fallback image across the whole site, and the default for all blog posts. Thanks for updating the homepage - I think that was set when we did the site transition.

**Comment by cjyabraham** [comment]
Ok.  It is set to be the fallback image across the whole site, including blog posts.
