### ISSUE TITLE
Create a button Gutenberg block with an expiry date that makes it disabled after that date

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#511]
[Inspect](https://events.linuxfoundation.org/prestocon/) [various](https://events.linuxfoundation.org/lf-member-summit/) [events](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/) to see how buttons are used in the hero image.  Create a button block exactly like these buttons but have an expiry date that can be set to make the button disabled on the front-end after that date, similar to the new alert block.  Allow the editor to enter different button text to show on the button once it is disabled.  Call the Gutenberg block "Button with Expiry".
 
Use the same techniques, naming conventions etc. to keep things consistent with the other Gutenberg blocks you've created.

No need to reproduce the Stackable button with all its many settings.  Just create a simple button that looks like the ones we've been using and has basic color settings.  We do need to make sure that buttons can be placed side-by-side like in [this event](https://events.linuxfoundation.org/prestocon/).

**Comment by cjyabraham** [comment]
Take note of the [new button block released in Gutenberg 7.2](https://wptavern.com/gutenberg-7-2-adds-long-awaited-multi-button-block-and-gallery-image-size-option) that allows for buttons side-by-side.  Maybe you could use their code and add the expiry date functionality?  Just an idea.

**Comment by rodmeurer** [comment]
@cjyabraham it's done.

https://pr-512-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

It's possible to align horizontally more than one button as you can see above. You must use the block "Group" to keep the buttons in the same container.

![image](https://user-images.githubusercontent.com/54405402/76110467-58b5f980-5fbd-11ea-926b-638a324ed46d.png)

Also it needs a CSS adjustment, so you need to add the class "**buttons"** to have the buttons aligned correctly.

![image](https://user-images.githubusercontent.com/54405402/76110600-87cc6b00-5fbd-11ea-8a9f-ac2ce0615e42.png)

**Comment by cjyabraham** [comment]
This is a good option.  Thanks.

Can you try another approach using the new Gutenberg Buttons block.  I just tried it out and it will ship with WP 5.4 on Mar 31.  Is there a way to hook into that block to add an expiry date on the buttons?  Alternatively, you could fork the block to add the expiry date?  

To get the Buttons block you can either install the [Gutenberg plugin](https://wordpress.org/plugins/gutenberg/) or upgrade WP to [5.4-RC1](https://wordpress.org/news/2020/03/wordpress-5-4-release-candidate/).  I think it's worth trying out this approach as the UX is very nice and it doesn't require the editor to add a CSS class etc.

Also, please take note of the updated description of this issue.  I may have changed it since you last looked.  We actually don't want the button to disappear.  We want it to become disabled and for the text to change.

**Comment by fuerzastudio** [comment]
hi @cjyabraham 

We tested the Gutenberg plugin and WP 5.4-RC1, both will work.
As we discussed yesterday, the best option is the WP upgrade, here goes a video showing the tests.
https://www.loom.com/share/e2cf85a87eba497593b8bcf339f7bfa5

After the upgrade no other action is necessary.

**Comment by cjyabraham** [comment]
Ok, great.  We can wait for the WP upgrade in a couple of weeks before merging.

Can you make the text that shows after expiry configurable?  And can you setup your PR instance so that we can play around with it?  For now, you can just include the Gutenberg plugin to get it to work?

**Comment by rodmeurer** [comment]
@cjyabraham it's all done. Plugin added and text configurable.

Example: https://pr-512-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

Admin: https://pr-512-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=817&action=edit

**Comment by cjyabraham** [comment]
Thanks.  I am setting this blocked until we upgrade to WP 5.4.

**Comment by cjyabraham** [comment]
I've been looking at the styles of the buttons here.  Can we make a few adjustments:
- Since the buttons are on top of an image, can we avoid use opacity for hover or disabled states?  So keep the opacity at 1 and for hover, make the button background brighter or darker.
- For an expired button, can we disable it using [these styles](https://material.io/design/interaction/states.html#disabled).  So elevation of the button is reduced to 0 and the background and text colors can be copied from [that example](https://material.io/design/interaction/states.html#disabled).
- in mobile screens, the buttons don't seem to fit properly inside the viewport:
<img width="419" alt="Screen Shot 2020-03-24 at 2 12 37 PM" src="https://user-images.githubusercontent.com/463160/77394154-97c7b580-6dd9-11ea-83f0-a054bcb5f201.png">

Can you try out these suggestions?

**Comment by rodmeurer** [comment]
@cjyabraham let us know if this is what you're expecting

https://pr-512-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

**Comment by cjyabraham** [comment]
Looking really good.  A few more thoughts:
- I created a normal button just below the hero called "I like how this button looks".  Can we inherit most of those styles.  Specifically I like the shadow on the button and like the hover state.  Note that on hover only the background color changes.  The text color stays the same and the shadow doesn't change.  I think this is how it should be.  I do like the size of the font on your buttons so I think we could keep that. 
- Is it possible to get "Buttons" and "Buttons with Expiry" blocks to use the exact same styles so that we can be consistent throughout the site?  Alternatively, could you just extend the "Buttons" block to add the expiry date so we only need one block?  You could have a "This button expires" checkbox that defaults to unchecked.  When it is checked then the expiry date and text applies.
- can you remove the drop-shadow from the disabled buttons so it complies with [these styles](https://material.io/design/interaction/states.html#disabled) and has zero elevation
- can you experiment with a "pressed" state such as [what is suggested here](https://material.io/design/interaction/states.html#pressed) or having a small tap effect on click, achievable by adding  position: relative; top: 1px; to the active state

**Comment by rodmeurer** [comment]
@cjyabraham we've made the style adjustments. We have tried to extend the "Buttons" block before and it doesn't worked properly, so we've created the "Buttons with Expiry" block.

So, we kept both blocks with the same styles to make them consistent as you suggested.

https://pr-512-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

The "I like how this button looks" button is using the "Buttons" block. The other ones are using the "Buttons with Expiry" block, just to confirm.

**Comment by cjyabraham** [comment]
Looking great now. Thanks.

**Comment by cjyabraham** [comment]
I have upgraded WP to 5.4 and merged in these buttons.  After doing so, the buttons-with-expiry didn't look the same as the normal buttons, so I made some [style](https://github.com/LF-Engineering/lfevents/commit/7decd7f059d9387e9ee7fa7c7d0fa165504b92d4) [tweaks](https://github.com/LF-Engineering/lfevents/commit/8ebb3c6bf14090ed757c0a14400108ea3fecb48c) and also [fixed a js error](https://github.com/LF-Engineering/lfevents/commit/3a0143aec880c31a097105f602efb34b2479e913).  I also got them to look the same in the admin.

Can you open a new PR and fix the following issues:
- when a normal Button block is created, if no colors are explicitly set, then they default to blue with white text.  Can you make the button-with-expiry do the same?
- is it possible to avoid having [js style the buttons](https://github.com/LF-Engineering/lfevents/blob/master/web/wp-content/themes/lfevents/src/assets/js/button-with-expiry.js)?

**Comment by rodmeurer** [comment]
@cjyabraham we adjusted the default colors for button-with-expiry, removed the js and fixed a bug with gradients after the update.

https://pr-532-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

Button 1 - the colors are set
Button 2 - with the default colors
Button 3 - with gradient fixed

**Comment by cjyabraham** [comment]
@rodmeurer you removed the js but didn't provide an alternate method of styling the expired button.  Can you accomplish the same style (no shadow) without the js?

If I set the background color and set a link but do not set the text color of a button, the text color defaults to black.  Can you make sure all buttons have white text by default?

If I set a background color but not the text color, the text color turns black on hover.  Can you prevent any text color changes on hover?

**Comment by rodmeurer** [comment]
@cjyabraham 

We were able to maintain the expired button style without js.
There's only one problem with the hover:

If the user selects one of the colors that appears there by default, it works well because there are already classes associated with those colors, so we can control this without any problem.

But, if the user goes to the custom option and selects any other random color, that color is passed directly to the element, then we cannot pre-set a darker shade for hover, only if we use JS.

So we need to know what you prefer.

We created some buttons for testing:
https://pr-532-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

**Comment by cjyabraham** [comment]
I think it's fine to leave the hover as is, without the use of js.

When a button with a gradient expires, it doesn't turn the background gray.  Can you have it turn gray please?

**Comment by rodmeurer** [comment]
@cjyabraham fixed! The 3rd button is an example of a button with gradient that expired.

https://pr-532-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

**Comment by cjyabraham** [comment]
Thanks.  Deployed.
