### ISSUE TITLE
Put countdown block css into the lfevents theme so that it gets included and compiled in app.css rather than having its own file

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#516]

**Comment by rodmeurer** [comment]
@cjyabraham Done!

PR: https://github.com/LF-Engineering/lfevents/pull/518
Example: https://pr-518-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

**Comment by cjyabraham** [comment]
Looks good.  Thanks.

Deployed.
