### ISSUE TITLE
Add GDPR ribbon and opt-out information

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#519]
Copy what they have on lf.org for the ribbon and [opt-out info](https://www.linuxfoundation.org/cookies/).

Options for implementation:
1. [GDPR Cookie Consent Plugin](https://www.webtoffee.com/product/gdpr-cookie-consent/): allows for  cookie opt-in settings and blocking scripts as requested, Location based exclusion of cookie notice, etc.  Seems very heavy and could slow site.
2. Copy what's done on https://www.linuxfoundation.org/: use must configure cookie settings via browser.  Fast but has fewer features.
3. There are [some other plugins](https://wordpress.org/plugins/gdpr-cookie-compliance/) which also seem feature rich but heavy.  Here's a list of [plugins that are picked because they are light](https://www.questioncage.com/best-wordpress-gdpr-plugins/).

**Comment by thetwopct** [comment]
I mostly recommend a 3rd party system - https://www.cookiebot.com. They auto-scan cookies regularly and update the acceptance, geo-target, respect DNT, meet accessibility standards, offer bulk consent for multiple domains (that's probably useful), multilingual...

They don't have dedicated non-profit information on their site, but they say to get in touch https://support.cookiebot.com/hc/en-us/community/posts/360014831313-Non-Profit-Organizations 

I've also used this library a few times and style it to the suit the client:

https://github.com/ipatate/gdpr-cookies
Demo: https://gdpr-cookies.now.sh

This script blocks 3rd party services from loading until consent is given or user interacts with site (which is deemed as acceptance), and can conditionally load scripts from an options modal. Slick.

But it may not be best suited to our needs as all LFE tracking is done via GTM, so the options to separate out what tracking is accepted by the user is greatly reduced (as the tracking scripts need to be inserted via JS). 

Using GTM for tracking creates a problem for most other cookie plugins too, so with any plugin I would expect some manual work will always be required to set and maintain a more complex system. This is why an automated solution like cookiebot works well.

**Comment by cjyabraham** [comment]
[Another option](https://wpspeedmatters.com/fastest-cookie-consent-wordpress-plugin/)

**Comment by cjyabraham** [comment]
As per our discussion, the team wants to keep this as simple as possible and essentially to reproduce the behavior of what we have on https://www.linuxfoundation.org/ and https://training.linuxfoundation.org/.

**Comment by cjyabraham** [comment]
@thetwopct , can you adapt [this option](https://wpspeedmatters.com/fastest-cookie-consent-wordpress-plugin/) for use by both the new cncf and current events sites?  The events site will need to display a Chinese translation of the text (use is_lfeventsci() to determine if you're on the Chinese site).  I will get the Chinese text.  All banners can point to [the LF cookies page](https://www.linuxfoundation.org/cookies/) which I will work with Craig to get updated.

**Comment by cjyabraham** [comment]
Chinese text:
- This website uses cookies to offer you a better browsing experience. Find out more about how we use cookies and how you can change your settings. 
本网站使用cookies为您提供更好的浏览体验。了解更多关于我们如何使用cookies和如何更改您的设置。
- Accept
接受

**Comment by cjyabraham** [comment]
An update from Kristin and LF legal:

> We have updated the LF privacy policy and cookie policy and are ready to deploy the call out ribbon on the bottom of the following websites: OSS NA, OSS EU, ELC NA, ELC EU, ONES NA, ONES EU. This can be identical to the one currently on www.linuxfoundation.org - look, links, copy, etc.

**Comment by cjyabraham** [comment]
I think the link should open in a new tab since it takes the user off the events site.

**Comment by cjyabraham** [comment]
deployed
