### ISSUE TITLE
Speakers block improvements

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#520]
As per our discussion, try the following design tweaks for feedback:
- Megan can put the [speakers block in a container](https://events.linuxfoundation.org/open-networking-edge-summit-north-america/program/featured-keynote-speakers/) to stop the colors from going to the edge of the screen.  She would, however, like the corners on the container to be softened/rounded.  Is this possible?
- Try a version of the speakers block that doesn't use gradient colors but instead uses more white as background.  (Note: we could still use the gradient for the heading block above the speakers block.)

**Comment by thetwopct** [comment]
I've added slight rounded corners to the Speakers Block when using `alignwide` alignment. 

I've added a "Plain" style which removes the gradient overlay from the block (so editors can have a solid colour background)

![2020-10-20-002009@2x](https://user-images.githubusercontent.com/10615884/96517892-084c8d00-126a-11eb-8aa2-d266aaa78e6c.png)
