### ISSUE TITLE
Kubecon sites are slow to load

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#530]
This appears to be something to do with cookies.  When you use an incognito window the pages load fast, suggesting that the average public user will not experience the problem.

**Comment by cjyabraham** [comment]
[Pantheon is investigating](https://dashboard.pantheon.io/users/3fd40f12-e3f9-41b1-bdd6-e01fe590de03#support/ticket/458179)

**Comment by cjyabraham** [comment]
@meganelizabethphillips @dankohn I've found the reason why the kubecon sites were loading slowly:

First, they were only loading slowly for us as we are Administrators on the site.  The public would receive cached copies of the site which would typically deliver in less than a second.  Even when we are not logged in our browsers usually submit a WordPress cookie and this breaks the cache and causes us to get an uncached version.  The only way around this is to clear browser cookies or use an incognito window.  But you don't have to worry about that because I found the underlying issue:

The root source of the issue was ShortPixel trying to convert all 140+ sponsor SVGs to WebP format as the page is loading.  This is crazy, first because we don't want SVGs converted to WebP, and second that it does this on page load.  So I've turned off the WebP feature for now and reported the issue to ShortPixel.

So you should now consistently experience the Kubecon sites load in [under 5s, rather than up to 20s](https://docs.google.com/spreadsheets/d/1hCProm1L9U7KXKGxOCOLrsZ7poITPvODb3BhH0vl7DE/edit#gid=0).  Let me know if you don't or if you have any questions about this.

I'll leave this issue open until ShortPixel gets back to me.

(CC @thetwopct as an FYI)

**Comment by meganelizabethphillips** [comment]
Thanks so much Chris!! Super helpful to know!

Megan Phillips, PMP
Events Web Project Manager
The Linux Foundation
1 Letterman Drive
Building D, Suite D4700
San Francisco, CA 94129
E: mphillips@linuxfoundation.org



Why Attend Linux Foundation Events <https://youtu.be/X_rLxfmLlYY>
Why Sponsor Linux Foundation Events <https://youtu.be/Rr-9cIH42fE>


_______________
*Upcoming Out of Office*
OOO: April 20 - 27 (no access to email/phone)

**Comment by cjyabraham** [comment]
Shortpixel just got back to me about this:

> Please advice Chris not to use that processing, but instead do it server based. For Nginx I believe there is some FAQ in our documentation that tells it how to do it, for Apache there is just the switch.

We can't configure nginx in Pantheon so for now I guess we'll just leave the webp functionality off.

**Comment by meganelizabethphillips** [comment]
Sounds good! Thanks for investigating further.

Megan Phillips, PMP
Events Web Project Manager
The Linux Foundation
1 Letterman Drive
Building D, Suite D4700
San Francisco, CA 94129
E: mphillips@linuxfoundation.org



Why Attend Linux Foundation Events <https://youtu.be/X_rLxfmLlYY>
Why Sponsor Linux Foundation Events <https://youtu.be/Rr-9cIH42fE>


_______________
*Upcoming Out of Office*
OOO: April 20 - 27 (no access to email/phone)
