### ISSUE TITLE
Newsletter block design

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#533]
@meganelizabethphillips  would like to have a second option for the layout of the newsletter form: full-width horizontal across the page and match what James designed for the footer:
<img width="1054" alt="Screen Shot 2020-04-15 at 1 31 29 PM" src="https://user-images.githubusercontent.com/463160/79301949-71e78980-7f1d-11ea-872e-4a0d03dcd631.png">

Add this as a "Layout" option to the existing Newsletter Form Gutenberg block.  It will have two values to choose from "Box" (the current format) and "Full-width" (the new format).  Is it possible to have the form rendered in the editor so you don't have to go to the front-end to see what it looks like?

If helpful, you can use [this code](https://github.com/LF-Engineering/lfevents/blob/footer/web/wp-content/themes/lfevents/src/assets/scss/modules/_footer.scss) which was used to format the above footer newsletter form.  [Here is a working example in the footer](https://pr-528-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/).

**Comment by deigolocco** [comment]
@cjyabraham could you validate please?
https://pr-541-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=817&action=edit
https://pr-541-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

**Comment by cjyabraham** [comment]
Thanks.  A few comments:
- Could you set the default layout to Box?
- I think the block should stack vertically at a wider width so that they don't get too small
- Could you avoid having the blocks lose the spacing between them as in here:
<img width="628" alt="Screen Shot 2020-04-22 at 10 00 54 AM" src="https://user-images.githubusercontent.com/463160/79932494-38180500-8480-11ea-96cf-a242764f8527.png">

**Comment by meganelizabethphillips** [comment]
Agree with all of @cjyabraham feedback. In addition, can we also have the button style mirror more of what we are using on the page (ie rounded corners)?

**Comment by rodmeurer** [comment]
Done @cjyabraham 

https://pr-541-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/

**Comment by cjyabraham** [comment]
Deployed.

@meganelizabethphillips please test thoroughly the first time you use the newsletter to make sure the entries are getting into the SF campaign.
