### ISSUE TITLE
Remove all shadows from the site

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#544]
This should be done for buttons and topnavs.

**Comment by cjyabraham** [comment]
@meganelizabethphillips I've got this working on [a dev instance here](https://pr-545-lfeventsci.pantheonsite.io/).  You can see some of our new buttons [here](https://pr-545-lfeventsci.pantheonsite.io/xen-summit/).

It's not completely perfect, the hover on the global topnav still has a shadow on some breakpoints, but should be good enough for Kristin and yourself to make a decision on whether you want this.

**Comment by meganelizabethphillips** [comment]
HI @cjyabraham ! Kristin loved this - lets remove the shadows please, and the button shadows too! Thank you!

**Comment by cjyabraham** [comment]
deployed
