### ISSUE TITLE
Add Flying Scripts plugin

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#563]
Set with the same settings as the lfph site and then test the forms thoroughly.  Do a before/after performance test.

**Comment by cjyabraham** [comment]
I have deployed this and set the sfmc-forms and recaptcha scripts to be delayed.  I'm surprised, however, to see that the performance gains are a lot more modest than [those on lfph](https://github.com/lfph/lfph.io/issues/32).

[Here are the before/after load time tests](https://docs.google.com/spreadsheets/d/1hCProm1L9U7KXKGxOCOLrsZ7poITPvODb3BhH0vl7DE/edit#gid=734557291).

And I used lighthouse to test as well:

**Before Kubecon page**
<img width="529" alt="kubecon wo fs" src="https://user-images.githubusercontent.com/463160/89703915-f86b1f80-d981-11ea-8aaa-f3bfc90b9b2f.png">
**Kubecon page with Flying Scripts**
<img width="579" alt="kubecon w fs" src="https://user-images.githubusercontent.com/463160/89703925-0faa0d00-d982-11ea-9b46-e4ab7b97748d.png">

**Before Homepage**
<img width="836" alt="homepage wo fs" src="https://user-images.githubusercontent.com/463160/89703917-fb661000-d981-11ea-8e25-d488303ec51c.png">
**Homepage with Flying Scripts**
<img width="608" alt="homepage w fs" src="https://user-images.githubusercontent.com/463160/89703929-1d5f9280-d982-11ea-8d3f-22c3db41493a.png">

**Comment by thetwopct** [comment]
Scores via web.dev/measure using Lighthouse 6 

## Homepage

![20200808105406-Measure](https://user-images.githubusercontent.com/10615884/89707402-7d940b80-d965-11ea-98c0-6a198bf5b45a.jpg)

[View report](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fevents.linuxfoundation.org) 

## Kubecon

![20200808105633-Measure](https://user-images.githubusercontent.com/10615884/89707443-d499e080-d965-11ea-9c09-b12fe532cce7.jpg)

[View report ](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fevents.linuxfoundation.org%2Fkubecon-cloudnativecon-europe%2F)

**Comment by cjyabraham** [comment]
I did the test using web.dev on the live site, w and wo Flying Scripts, flushing cache between attempts and running the test twice and taking the second run.

**Homepage wo FS**
<img width="1017" alt="home wo fs" src="https://user-images.githubusercontent.com/463160/89723143-fdcd7600-da24-11ea-9283-1268d4124217.png">

**Homepage w FS**
<img width="1013" alt="home w fs" src="https://user-images.githubusercontent.com/463160/89723144-03c35700-da25-11ea-9e06-6d685c6b3249.png">


**Kubecon wo FS**
<img width="1012" alt="kubecon wo fs" src="https://user-images.githubusercontent.com/463160/89723132-ee4e2d00-da24-11ea-8fd7-4725d181d22c.png">

**Kubecon w FS**
<img width="1006" alt="kubecon w fs" src="https://user-images.githubusercontent.com/463160/89723136-f5753b00-da24-11ea-96b9-1c88ee776ee4.png">

**Comment by cjyabraham** [comment]
WRT the [LFPH issue](https://github.com/lfph/lfph.io/issues/32) and this one, I think what we're seeing here is that there are much larger performance gains on pages that have an active form while the gains on pages without a form are small.  When there is a form there are more js files that are downloaded, so FS is giving us more of an advantage.  Because forms are soon going to be ubiquitous on the events site, this performance gain will be more widespread.
