### ISSUE TITLE
Check to see if Safe SVG plugin has been updated

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#567]
I forked [the safe-svg plugin](https://wordpress.org/plugins/safe-svg/) due to #546.  I should see if the author has integrated my change.  Check [the thread here](https://wordpress.org/support/topic/slow-performance-of-svg_dimensions-function/).  If not, I could encourage the author to do that or fork it again to get the updates and re-apply [my patch](https://github.com/LF-Engineering/lfevents/commit/b31835692a5b79b0431f4a7b0f8957d284dee32e).

**Comment by cjyabraham** [comment]
It basically looks abandoned.  Craig is considering [wp-svg-images](https://wordpress.org/plugins/wp-svg-images/) as a replacement.

**Comment by thetwopct** [comment]
[wp-svg-images](https://wordpress.org/plugins/wp-svg-images/) looks good, but from what I can see offers no sanitisation of the SVG files, and I would consider that a "must-have" aspect.

**Comment by cjyabraham** [comment]
Safe SVG is now being developed by 10up. I have [re-opened my old performance issue](https://wordpress.org/support/topic/an-old-performance-issue/) to see if they can incorporate my fix.

**Comment by thetwopct** [comment]
@cjyabraham Seems the Safe SVG plugin has [been update a bit](https://github.com/10up/safe-svg/blob/develop/CHANGELOG.md) (although your raised issue has not been directly addressed). I wonder if its worth us updating the plugin and the reapplying your patch?

**Comment by cjyabraham** [comment]
Sounds good!

**Comment by cjyabraham** [comment]
I've [upgraded SafeSVG to v. 2.2.1](https://github.com/LF-Engineering/lfevents/commit/116926fabced36e5feab4a8c472a614ef1d9f440) and [re-applied my patch to avoid performance issues](https://github.com/LF-Engineering/lfevents/commit/198ba4a289d4318a508ca2dce677c8e1247d9783). This allows us to benefit from recent advances of the plugin.

I'll leave this issue open until the SafeSVG team has integrated a proper fix for [the issue](https://github.com/10up/safe-svg/issues/75).

**Comment by cjyabraham** [comment]
The underlying issue has been fixed, so once we install the [2.3.0 version of the plugin](https://github.com/10up/safe-svg/milestone/10) we won't need our patch anymore.

**Comment by cjyabraham** [comment]
Looks like [the 2.2.3 version](https://github.com/10up/safe-svg/releases/tag/2.2.3) has included a fix for this.

**Comment by cjyabraham** [comment]
We're now back on the main versions of this plugin
