### ISSUE TITLE
Fix 404s and link issues on the events19 site

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#569]
- https://events.linuxfoundation.org/travel-fund-request/ now directs people to a 404 on events19
- the "Travel Fund" link [on this page](https://events19.linuxfoundation.org/events/open-source-summit-europe-2019/attend/scholarships/) goes to a 404
- this page still shows up in search results: https://events19.linuxfoundation.org/travel-fund-request/uploads/

**Comment by surajkulriya** [comment]
Hello sir I want to contribute in this open source project can you please help me in getting started with .

**Comment by cjyabraham** [comment]
These issues are now resolved.
