### ISSUE TITLE
Site performance

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#585]
Following up from [the outstanding performance of cncf.io](https://www.cncf.io/blog/2020/10/08/a-better-faster-cncf-io/), let's see if we can get the events homepage to score in the 90s.  Here are the current scores:
<img width="600" alt="Screen Shot 2020-10-08 at 10 58 20 AM" src="https://user-images.githubusercontent.com/463160/95409866-34f0d280-0955-11eb-9fa2-337f7936305d.png">

And we can also look at the [Kubecon homepage](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/) which gets these scores:
<img width="600" alt="Screen Shot 2020-10-08 at 10 59 31 AM" src="https://user-images.githubusercontent.com/463160/95409969-61a4ea00-0955-11eb-9f3e-c04720ad0fb6.png">

**Comment by thetwopct** [comment]
## Home page

(tested on dev instance, so production might be better)

<img width="989" alt="2020-11-15-001833@2x" src="https://user-images.githubusercontent.com/10615884/99158900-232ee780-26d8-11eb-80d4-1410c82d51de.png">

A little better, but not much. The image slider using css background images is killing us (can't use srcset, can't lazy load them even though they are off-screen) and no webP.

**Comment by thetwopct** [comment]
## Event pages

Seems the Kubecon NA event got worse... 

<img width="618" alt="2020-11-15-182955@2x" src="https://user-images.githubusercontent.com/10615884/99191994-9c7a1900-2770-11eb-9666-569f08cd632f.png">

I've added some lazy loading to the images, including all the sponsor logos, but it doesn't do much. 

Revised on dev instance:

<img width="985" alt="2020-11-15-184024@2x" src="https://user-images.githubusercontent.com/10615884/99192222-0cd56a00-2772-11eb-8c8f-9a5bba907d42.png">

Once I fix the Lite YouTube Embed Block for editors, we can also use that going forward for YouTube embeds which should remove a lot of excess that the video brings. Other than that, the Cover block not using srcset is a bit of a killer, no lazy loading.

**Comment by cjyabraham** [comment]
Looks like we're up to 47 on Kubecon now after Stackable has been removed:
![Uploading Screen Shot 2020-11-16 at 4.28.30 PM.png…]()

**Comment by cjyabraham** [comment]
I see two outstanding tasks:
- [ ] Bring over the Youtube lite block when [it's fixed](https://github.com/cncf/cncf.io/issues/341)
- [ ] See if there's appetite to rewrite the homepage slideshow to make it performant

**Comment by cjyabraham** [comment]
Here's the new measurements for the homepage sans slideshow.  How much is the new topnav and SSO js slowing us down?
<img width="1002" alt="Screen Shot 2020-12-04 at 1 10 06 PM" src="https://user-images.githubusercontent.com/463160/101124476-21e73f80-3632-11eb-9825-66e7b55c5bdf.png">

**Comment by thetwopct** [comment]
The home page as of Saturday 16th January 2021:

![2021-01-16-212950@2x](https://user-images.githubusercontent.com/10615884/104823451-fd41d280-5841-11eb-902c-0031b625a657.jpg)

![2021-01-16-172117@2x](https://user-images.githubusercontent.com/10615884/104818398-49c7e680-581f-11eb-87af-e6bad906bfb3.jpg)

Seems the page is automatically preloading other pages via Flying Pages, so I updated the settings for it to not preload anything for 5 seconds, or until a user hovers over a link.

![2021-01-16-172251@2x](https://user-images.githubusercontent.com/10615884/104818434-8eec1880-581f-11eb-8f0d-8cd9d4082ac7.jpg)

Same effect, less stress on initial page load. As there are a lot of links on the home page we could even evaluate turning off the initial loading and exclusively use mouse hover to action a preconnect.

After changing this setting:

![2021-01-16-213428@2x](https://user-images.githubusercontent.com/10615884/104823521-a12b7e00-5842-11eb-917e-9d4f1d34a7b5.jpg)

![2021-01-16-172724@2x](https://user-images.githubusercontent.com/10615884/104818548-25b8d500-5820-11eb-97f7-c1b79d4817d6.jpg)

(GT Metrix score is on a desktop computer/fast internet, whereas Lighthouse uses smartphone/typicaly network speed.)

## Full Story 
FS accounts for a large chunk of total render blocking time ☹️
![2021-01-16-171502@2x](https://user-images.githubusercontent.com/10615884/104818268-80513180-581e-11eb-8589-4c9fa516f00b.jpg)

Sometimes a massive chunk depending on their server responses

![2021-01-16-174821@2x](https://user-images.githubusercontent.com/10615884/104819065-17b88380-5823-11eb-848e-7d0a76a33446.jpg)

I've made some further changes which I will test on a PR.

**Comment by thetwopct** [comment]
Got a few more pips out of it with some changes, and this is on the PR uncached and unminified 
![2021-01-16-235909@2x](https://user-images.githubusercontent.com/10615884/104827577-ec4f8c00-5856-11eb-98d0-c294f001c6c2.jpg)

**Comment by cjyabraham** [comment]
FullStory will just be used temporarily.  I'll uninstall it once we get enough data to analyze.

**Comment by thetwopct** [comment]
On production after last PR deploy, the accessibility changes have come through nicely, but performance is still taking a hit.

![2021-01-19-092612](https://user-images.githubusercontent.com/10615884/105014582-84589b80-5a38-11eb-8f54-ab78129b32bd.jpg)

I've added a preconnect to see if that helps full story and new relic. We can remove it/update the code when we merge in the hubspot preconnects.

**Comment by cjyabraham** [comment]
Current status looking pretty decent so I'll close this issue out for now.
<img width="986" alt="Screen Shot 2021-05-17 at 2 52 02 PM" src="https://user-images.githubusercontent.com/463160/118444241-77fef980-b71f-11eb-9d50-dce075bb0dce.png">
<img width="981" alt="Screen Shot 2021-05-17 at 2 51 22 PM" src="https://user-images.githubusercontent.com/463160/118444252-7af9ea00-b71f-11eb-9ddc-643572704227.png">
