### ISSUE TITLE
Activate the alignment selector for the Speakers block

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#592]
Speakers blocks are sometimes placed in Containers in order to limit their width, [such as here](https://pr-580-lfeventsci.pantheonsite.io/embedded-linux-conference-europe/program/featured-speakers/).  Instead of requiring a container, can you activate the alignment selector for the block and style appropriately:
<img width="269" alt="Screen Shot 2020-10-17 at 11 35 23 AM" src="https://user-images.githubusercontent.com/463160/96327544-13869980-106d-11eb-8e34-dfd71fbc77c7.png">

I think we just need wide width and full width.

**Comment by thetwopct** [comment]
I've activated the alignment on Speakers Block, and [set up some examples](https://pr-580-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/attend/who-should-attend/).

Let me know any updates (do we need centered? and if so, what should it look like?)

**Comment by thetwopct** [comment]
Megan couldn't see a use-case for the "centered" alignment, so I've removed it.

**Comment by cjyabraham** [comment]
Can you round the corners on the hover overlay as well?
<img width="711" alt="Screen Shot 2020-10-25 at 9 52 54 AM" src="https://user-images.githubusercontent.com/463160/97097127-f7f04400-16a7-11eb-8f74-60cacd6c15f7.png">

The settings are a bit confusing.  When I select two different colors I see a gradient, no matter whether "Gradient" or "Plain" style is chosen.  It seems there are multiple gradients being employed and the style setting only seems to control one of them?  Is there a way to simplify that?

When I place a new block on the page, its tool bar shows it to be in "Wide" width, however, on the front end it appears in full-width.  Could we make these consistent, one way or the other, from the time you put the block on the page?

**Comment by thetwopct** [comment]
1) Got rid of corner overflow on hover
2) Not sure I follow. But I made a video to show my intentions https://cln.sh/04GOnB if you're expecting something else or want something else let me know. I can't see how it can be made simpler with the current parameters.
3) Set to wide as default when no setting selected.

**Comment by cjyabraham** [comment]
On 2, I see what you're saying.  Let's leave for now until we get feedback from Megan.  I'll close out this issue.  All else looks good!
