### ISSUE TITLE
Embedded Google Docs iFrame doesn't work properly on mobile

### ISSUE THREAD

**Issue by thetwopct** [LF-Engineering/lfevents#593]
Commonly used on "Who's Coming" pages - [for example](https://events.linuxfoundation.org/embedded-linux-conference-europe/attend/whos-coming/) - a Google Doc is embedded via iFrame on page.

On mobile, this doesn't responsively update and there is no scroll overflow, so users cannot view the document.

<img width="321" alt="2020-10-19-224112@2x" src="https://user-images.githubusercontent.com/10615884/96509389-39be5c00-125c-11eb-90f1-6da9558400a7.png">

**Comment by thetwopct** [comment]
A Google Doc when embedded has the page margins around it, which explains the indented text in the screenshot. I can't find a way around that other than editing each document to update the margins to a minimal value. 

Embedding the Google Doc using the [iFrame block](https://github.com/cncf/wp-mu-plugins/tree/master/lf-blocks/src/iframe) from LF MU does at least activate an overflow scroll for the user to scroll - but for a 2  column list, there is no reason why it shouldn't fit on the page.

Embedding a Google Sheet does not include any page margins, so looks better on the page:

<img width="368" alt="2020-10-23-151352@2x" src="https://user-images.githubusercontent.com/10615884/97007896-64513300-1542-11eb-8f4d-b2d31a5edd3b.png">

Meghan mentioned two things:

1. They wanted to be able to easily update "Who's coming" - but the reality is she will copy and paste the entire list each time as its too difficult to update individual changes
2. The original idea of using an embed was so prevent copying the data (not sure how that worked anyway), but as the data is now anonymised, there is little need for this requirement.

Solutions:
- Using a Google Sheet embed (I can copy across iFrame embed from CNCF LF MU)
- Paste the data directly in to the page (possibly create a dedicated style for the table)

**Comment by cjyabraham** [comment]
@meganelizabethphillips any thoughts on which solution to pursue?

**Comment by cjyabraham** [comment]
As per Megan, since some of the lists will be super-long we should go with the embed Google Sheets solution.  And LMK when you copy across that CNCF iFrame block as that will be useful as well when we embed emails lists.

**Comment by cjyabraham** [comment]
I have merged the branch and deleted it optimistically, however, there are still some things that need fixing before we deploy. 
 You might as well do these directly on `master`:
- [ ] iFrame Max Width doesn't seem to be respected on the front-end; it's fine in the editor; see [this one for example](https://dev-lfeventsci.pantheonsite.io/riscv-global-forum/iframes-and-lists/); weirdly, it seems fine on [the homepage subpages](https://dev-lfeventsci.pantheonsite.io/2020/12/15/iframes-and-lists/)
- [ ] I suggest the Google Sheet style have "Remove Padding on right" selected by default
- [ ] Can you turn off the alignment selector for the block?  It doesn't seem to do anything except for moving the iframe to the left edge of the browser on "full width"

**Comment by thetwopct** [comment]
- Max width seems to work frontend and backend
- Removed alignment options
- Padding right default options fixed

Testing
https://dev-lfeventsci.pantheonsite.io/2020/11/13/linux-foundation-events-monthly-snapshot-november-2020/
https://dev-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=82343&action=edit

https://dev-lfeventsci.pantheonsite.io/dpdk-summit-apac/attend/coming/
https://dev-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=91970&action=edit

The use of blanket `!important` statements littered through the theme is `100% !important` a thing to fix to make this theme manageable. Technical debt that bites us consistently.

**Comment by cjyabraham** [comment]
The Max width still seems to behave differently on mobile.  Both of the following have max width set to 70%:
1. [homepage subpage](https://dev-lfeventsci.pantheonsite.io/2020/12/16/mo-iframs/); on mobile, this one stays at 70% width
2. [event page](https://dev-lfeventsci.pantheonsite.io/edgex-foundry-hanoi-release-planning-conference-spring/show-me/); on mobile, this one fills full width.

I'm not too bothered which way you go but I think they should be consistent.  I'd probably pick 2.

**Comment by thetwopct** [comment]
Where the examples I setup not good enough for you 😂

**Comment by thetwopct** [comment]
They should be consistent now

**Comment by cjyabraham** [comment]
I'd call it a masterpiece!
