### ISSUE TITLE
Add more colour options to the Table block

### ISSUE THREAD

**Issue by thetwopct** [LF-Engineering/lfevents#594]
Megan has requested a broader range of colours used on the Table block.

I thought this would be straightforward, but it seems that the pale colours are built-in to the block and not editable. They sync with the "striped" table style and provide high contrast for accessibility (we don't use the striped style as it clashes with the default table styling). The issue is replicated on CNCF.

<img width="279" alt="2020-10-22-162052@2x" src="https://user-images.githubusercontent.com/10615884/96885140-9a2ee280-1482-11eb-88e5-5bc278c2fbda.png">

Seems this is a known issue, but no progress is happening with solutions:

https://github.com/WordPress/gutenberg/issues/19659
https://github.com/WordPress/gutenberg/issues/16478

Solutions for us: 
- Apply more colours via Block Styles (perhaps we have 2 event-colour generated styles, plus a couple more generic pastel colours?)
- Fork the block and add in the full colour palette

**Comment by cjyabraham** [comment]
What's the use-case @meganelizabethphillips is needing a broader range of colors for?  Is there an alternate path to meeting that use-case that doesn't require additional colors?

**Comment by thetwopct** [comment]
The objective is to have colours for table backgrounds that are more inline with the colours used for a particular event or colours more suited to LF style.

A use case could be the Slack channel tables. If 6 tables are used, there are only 4 colours to choose.

**Comment by cjyabraham** [comment]
In that case I'd just go with adding extra styles for now.  I assume sooner or later this will get fixed in core.

**Comment by cjyabraham** [comment]
In terms of changing the table background color, can't the table just be put inside of a Group block with the background color set?

**Comment by meganelizabethphillips** [comment]
I don't know enough about how group blocks work to be able to say yes or
no. Previously a group block was when you selected a bunch of existing
blocks and grouped them together. I was unaware you could set a background
color - is this an update in the new version?

Thanks!

Megan Knight (Phillips), PMP
Events Web Project Manager
The Linux Foundation
1 Letterman Drive
Building D, Suite D4700
San Francisco, CA 94129



Why Attend Linux Foundation Events <https://youtu.be/X_rLxfmLlYY>
Why Sponsor Linux Foundation Events <https://youtu.be/Rr-9cIH42fE>

**Comment by cjyabraham** [comment]
The Group block is almost equivalent to the Stackable Container block.  You can set text and background colors etc.  [Here are several examples of how we can use it going forward](https://new-way-lfeventsci.pantheonsite.io/kubecon-cloudnativecon-north-america/container/).

**Comment by thetwopct** [comment]
Closing this issue, as since WordPress 5.8, tables can now have any color set as the background
