### ISSUE TITLE
Timer Expired messaged on frontend from Countdown Block

### ISSUE THREAD

**Issue by thetwopct** [LF-Engineering/lfevents#603]
The Countdown Block that is used for events displays a message "Timer Expired" on the frontend to public users

<img width="1306" alt="2020-11-18-201535@2x" src="https://user-images.githubusercontent.com/10615884/99583093-ebc38200-29da-11eb-9c6f-42be28aa96ac.png">

If no post-expiry message is set, should it instead display nothing to public users?

**Comment by cjyabraham** [comment]
Agreed.  @meganelizabethphillips ?

**Comment by cjyabraham** [comment]
deployed
