### ISSUE TITLE
Sticky menu doesn't always reset

### ISSUE THREAD

**Issue by thetwopct** [LF-Engineering/lfevents#609]
![2020-11-25-174646@2x](https://user-images.githubusercontent.com/10615884/100264057-35b1e800-2f46-11eb-89f5-069b9222d6e3.jpg)

1. Home page
2. Scroll down
3. Scroll back up
4. Gap appears

Using Safari 14 on Mac

Issue seems to stop when `@include foundation-sticky;` is removed from `app.css` so possible fix could be to replace the sticky library in use

**Comment by cjyabraham** [comment]
I can reproduce on Safari but not any other browser.

**Comment by cjyabraham** [comment]
FYI this doesn't seem to be a problem on individual Events

**Comment by cjyabraham** [comment]
Seems fixed on the new topnav.
