### ISSUE TITLE
Implement hero images on all non-event pages

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#611]
- [x] Implement [these designs](https://www.figma.com/file/2mfeSLBLkYCVPdMMc15Yjn/Events-Mock) for all non-event pages for both the main site and lfasiallc
- [x] Test performance of site before and after this change
- [x] Update Admin instructions (Chris)

I figure we put the photo of Dan on the past events page, the photo of Cheryl on the homepage and the photo of that random girl on the calendar page and the random people on the sponsor page. 

Some other image ideas:
- https://www.flickr.com/photos/143247548@N03/48301899321/in/album-72157707188120301/
- https://www.flickr.com/photos/143247548@N03/46985432345/in/album-72157707188120301/
- https://www.flickr.com/photos/143247548@N03/48302166391/in/album-72157707188120301/ (flipped horizontally)

Image ideas for lfasiallc:
- https://www.flickr.com/photos/143247548@N03/48124146728/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48124198852/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48124193627/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48124111398/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48124119453/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48125125522/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48124063971/in/album-72157709241579017/ (flipped horizontally)
- https://www.flickr.com/photos/143247548@N03/48124060691/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48124037991/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48129910382/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48129807706/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48129794976/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48129816258/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48145659916/in/album-72157709241579017/
- https://www.flickr.com/photos/143247548@N03/48145634001/in/album-72157709241579017/

**Comment by thetwopct** [comment]
Looking at the Style Guide, I think the intentions were a gradient background for page heros, so this is the approach I've taken, with only the home hero getting text overlay on image. The Style Guide species a 60% opacity gradient, so correct image selection is quite important as otherwise white text can get lost, and I think having the image hero on every page could often make titles harder to read.
