### ISSUE TITLE
Don't include empty style.css

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#614]
[Style.css](https://events.linuxfoundation.org/wp-content/themes/lfevents/style.css?ver=5.4.2) is being sent to users even though it's empty because of [this commit](https://github.com/LF-Engineering/lfevents/commit/dce3832a739a2926f0ab8e7351d84e0d9282e322).  Can you attach inline styles to a different stylesheet as you suggest?

**Comment by thetwopct** [comment]
I've fixed this in one of the PRs
