### ISSUE TITLE
Group and Cover block styles

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#615]
- [ ] Get the group and cover blocks to match more.  Both should have rounded corners by default.
- [ ] Make the styles affect the display in the editor, not just on the front-end.

**Comment by thetwopct** [comment]
From Meghan

`I miss the container setting where I could change the alignment to only be the center 50% of the container vs needing to use a table within a group block`

- [ ] Look at adding constrained content Style to a Group block

**Comment by cjyabraham** [comment]
I think this will be good.  The current way of doing this with columns is imperfect as at a certain breakpoint the columns stack in an awkward fashion:
<img width="779" alt="Screen Shot 2020-12-17 at 12 54 02 PM" src="https://user-images.githubusercontent.com/463160/102445652-f5d2b200-4066-11eb-82d2-1a93d2df7050.png">
