### ISSUE TITLE
Section heading too short on mobile

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#618]
Looks like this didn't get translated properly when we went to Groups.

It should look like this:
<img width="362" alt="Screen Shot 2020-12-11 at 2 27 32 PM" src="https://user-images.githubusercontent.com/463160/101870655-07c2d980-3bbd-11eb-9817-7eef50d00133.png">
<img width="362" alt="Screen Shot 2020-12-11 at 2 31 46 PM" src="https://user-images.githubusercontent.com/463160/101870982-ac451b80-3bbd-11eb-8256-c48430da23af.png">

Instead it looks like this:
<img width="360" alt="Screen Shot 2020-12-11 at 2 27 59 PM" src="https://user-images.githubusercontent.com/463160/101870689-1610f580-3bbd-11eb-88b0-b6f38cbe0d54.png">
<img width="363" alt="Screen Shot 2020-12-11 at 2 32 04 PM" src="https://user-images.githubusercontent.com/463160/101870990-b0713900-3bbd-11eb-9954-3fae375eea77.png">

**Comment by thetwopct** [comment]
The original code for the Style `.is-style-one-line-section-heading` is a bit hacky, using negative margins to try to style the group around the H3. I've added a fix for this on mobile for now, but we may want to change this so either the group block isn't needed (apply the full width style to the H3 directly) or apply the style at the group level to affect the text contents.

**Comment by thetwopct** [comment]
This looks better now. Slightly less padding than the original was, but I think its more suited to mobile as it currently is
