### ISSUE TITLE
Improve the edit screen for the pricing table

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#619]
Note that it goes off the screen. [See here](https://events.linuxfoundation.org/wp/wp-admin/post.php?post=885&action=edit).  Note also that people are including a inline style to try and adjust the front-end:
<img width="1270" alt="Screen Shot 2020-12-11 at 3 12 33 PM" src="https://user-images.githubusercontent.com/463160/101874262-87ec3d80-3bc3-11eb-8f5e-9275f914be13.png">

**Comment by thetwopct** [comment]
Frontend issue 
https://pr-617-lfeventsci.pantheonsite.io/r-medicine/register/

![2020-12-18-134323@2x](https://user-images.githubusercontent.com/10615884/102621106-05b9c700-4137-11eb-8c91-9832c762ab43.jpg)

**Comment by cjyabraham** [comment]
Can you take the mobile font size for the prices down a notch.  The word "Complementary" is especially problematic:
<img width="309" alt="Screen Shot 2020-12-20 at 10 52 56 AM" src="https://user-images.githubusercontent.com/463160/102704036-95838080-42b1-11eb-931e-aeccea8bedcc.png">
