### ISSUE TITLE
Make events site topnav sticky on desktop

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#622]
The topnav on the events site has not been sticky since [this commit](https://github.com/LF-Engineering/lfevents/commit/de7a9489f554c8b0bccb08498559e93d5f4254c4).

**Comment by thetwopct** [comment]
Ah yes, event pages on mobile had a strange grey bar on the right of the screen at 360px width and below. The container requires overflow:hidden on it to get rid of it 🤷 Let me fix this.

(Side note: The commit you referenced was the branch merge. I wonder if its worth rebasing + merging in future so individual commits can still be referenced.)

**Comment by thetwopct** [comment]
OK this should be fixed. 

The non-event menu **is** sticky on mobile (but not landscape mobile).  For a 50px height menu I don't see this as being an issue for screen real estate, but its not currently inline with the event pages or with other LF properties (LFX/Training in their current forms anyway).
It makes sense to me for it to be sticky - if the menu is sticky on desktop, why wouldn't you want it on mobile too, especially when the process of getting to the top of the screen is much harder on mobile 🤷 (we also make no provision for back to top link and the non-event page footer menu doesn't reflect the header nav, which makes the menu even more important)

**Comment by cjyabraham** [comment]
Can you make it respect the wp-admin nav bar?  All other topnavs we have respect this bar and don't go behind it:
<img width="900" alt="Screen Shot 2020-12-16 at 12 52 19 PM" src="https://user-images.githubusercontent.com/463160/102306591-8fce2800-3f9d-11eb-95f0-ffa12398d63e.png">

**Comment by thetwopct** [comment]
Admin bar positioning fixed

**Comment by cjyabraham** [comment]
Something weird happens when you're logged in and you have a short viewport:
<img width="824" alt="Screen Shot 2020-12-16 at 8 55 41 PM" src="https://user-images.githubusercontent.com/463160/102351251-17895600-3fe1-11eb-861f-7330a493c43e.png">

**Comment by thetwopct** [comment]
I LOVE THIS THEME. Fixed now.

**Comment by cjyabraham** [comment]
deployed
