### ISSUE TITLE
Missing tab container template from archived events

### ISSUE THREAD

**Issue by thetwopct** [LF-Engineering/lfevents#625]
The tab container page template is not available to archived events

![image](https://user-images.githubusercontent.com/10615884/104240199-998b6400-5453-11eb-9b94-8e5259b412db.png)

We can activate it by adding the following to the top of multi-part-page.php file ([source](https://make.wordpress.org/core/2016/11/03/post-type-templates-in-4-7/))

```
/**
 * Template Name: Multi-part Page with Menu
 * Template Post Type: page, lfevent2016, lfevent2017, lfevent2018, lfevent2019, lfevent2020, lfevent2021
 *
 * @package FoundationPress
 */
```

This feature does not seem to support [fuzzy matching](https://github.com/WordPress/wordpress-develop/blob/31476dc27c3c2d9480d0cf09d7ec4aefd56ac262/src/wp-includes/class-wp-theme.php#L1189). I cannot find a solution where we can enable a template for an array of CPTs in a different way.

**Comment by cjyabraham** [comment]
Thanks.  I've enabled this template for events from 2019 onwards.  The older CPTs don't need it.  

Deployed.
