### ISSUE TITLE
Button with expiry is centred by default in editor 

### ISSUE THREAD

**Issue by thetwopct** [LF-Engineering/lfevents#627]
Button with expiry is centred by default in editor 
Noted by Megan on 14/01/21 call

**Comment by cjyabraham** [comment]
The button is centered in the editor when inserted but shows left-aligned on the front-end.  I think it should be left-aligned in the editor when inserted.  I think this is how it used to work.  At the least, it should be consistent with the front-end.

**Comment by thetwopct** [comment]
Needed some styling updates.

Frontend:
![2021-01-15-182003@2x](https://user-images.githubusercontent.com/10615884/104763767-51738680-575e-11eb-9d1a-19d8671bc2b6.jpg)

Backend:
![2021-01-15-181908@2x](https://user-images.githubusercontent.com/10615884/104763708-39036c00-575e-11eb-8738-8c6eee71faf2.jpg)

Looks fixed to me.

**Comment by cjyabraham** [comment]
Closed with the merge operation.
