### ISSUE TITLE
4:3 YouTube videos are not sized correctly

### ISSUE THREAD

**Issue by thetwopct** [LF-Engineering/lfevents#643]
4:3 YouTube videos are not sized correctly. 

Changing class (in advanced settings for embed block) from `wp-embed-aspect-4-3` to `wp-embed-aspect-16-9` fixes it in short term, but look to implement CSS solution so editors don't need to worry about it

![2021-04-01-204817@2x](https://user-images.githubusercontent.com/10615884/113346324-9b1a4900-932b-11eb-829d-5ce163be517f.jpg)

**Comment by cjyabraham** [comment]
These look fixed now here: https://events.linuxfoundation.org/openapi-asc/
