### ISSUE TITLE
Fix image-box Gutenberg block

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#648]
The Image-box Gutenberg block is no longer available in the block picker and existing blocks appear broken ([example](https://events.linuxfoundation.org/wp/wp-admin/post.php?post=101255&action=edit)).  Please also check to see if any of our other custom blocks need fixing in a similar way.

**Comment by cjyabraham** [comment]
Are there any similar changes that need updating on any of our other custom blocks?

**Comment by thetwopct** [comment]
I briefly tested each block and didn't see other issues. The problem with Image Box was related to the insertion of rel attributes on links and the way I was handling them in the save function.
