### ISSUE TITLE
Input is not visible when subscribing to mailing list 

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [LF-Engineering/lfevents#653]
**ScreenShot:**
![Screenshot from 2021-06-30 17-53-16](https://user-images.githubusercontent.com/43534227/123959809-32934480-d9cc-11eb-8c68-a43f766f5442.png)

**Description:**
As shown in screenshot you can barely see my `First Name` , `Last Name` & `Email id` because it's in black/grey colour which is being overlapped by blue background's color . 

**Solution:**
I am thinking to change colour of input text to white .

**OS:**
Ubuntu 20.04 LTS

**Browser:**
Google Chrome

**Page:**
https://linuxfoundation.org/ . In the footer section where subscribing to mailing list option is.

**Comment by cjyabraham** [comment]
@ccraigross ^

**Comment by Rishabhraghwendra18** [comment]
@cjyabraham may I work on this issue ?

**Comment by cjyabraham** [comment]
The issues concerns the https://linuxfoundation.org/ site which isn't this repo.  I don't think the code is open source for it so all we can do is alert @ccraigross .  Thanks for reporting it though!

**Comment by Rishabhraghwendra18** [comment]
> The issues concerns the https://linuxfoundation.org/ site which isn't this repo. I don't think the code is open source for it so all we can do is alert @ccraigross . Thanks for reporting it though!

Ok.. I thought website is open source 😥. No problem
