### ISSUE TITLE
Events dropdown menu is transparent

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#657]
For some reason "View all Events" dropdown menu is transparent on [this event](https://events.linuxfoundation.org/linux-kernel-maintainer-summit/):
<img width="427" alt="Screen Shot 2021-07-23 at 2 14 33 PM" src="https://user-images.githubusercontent.com/463160/126824458-d7ecbc82-9fa5-42ab-8ea7-c292688bc22f.png">

**Comment by cjyabraham** [comment]
Never mind.  The menu dropdown color is not set.  I've told Megan to set one.

**Comment by thetwopct** [comment]
We could set a default I guess?

**Comment by cjyabraham** [comment]
Sounds good
