### ISSUE TITLE
Block-based widgets screen throws an error

### ISSUE THREAD

**Issue by thetwopct** [LF-Engineering/lfevents#659]
A PHP error is throw on the new block-based widgets screen in WP 5.8: 

`wp_enqueue_script() was called incorrectly. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see Debugging in WordPress for more information. (This message was added in version 5.8.0.)`

Some history on this:
https://github.com/WordPress/gutenberg/issues/33576
https://core.trac.wordpress.org/ticket/53437
https://core.trac.wordpress.org/ticket/53664

Essentially any script or style enqueued with a dependency of `wp-editor` or `wp-edit-post` will cause the error to be thrown.

The Create Guten Block package we used for many early blocks references `wp-editor` as a dependency so I've gone through and removed that dependency from those plugins.

There are 2 third party plugins affected on LF Events:

- Conditional Blocks
- Post Meta Controls

Until they are updated, I'm going to revert the site to use the classic editor widget screen, using:

```
// Disable new widget screen.
remove_theme_support( 'widgets-block-editor' );
```

**Comment by cjyabraham** [comment]
Sounds good to disable.  I don't see us needing widgets any time soon.

**Comment by thetwopct** [comment]
We have disabled block based widgets for now so we should close this
