### ISSUE TITLE
Moving multiple blocks into a container produces Gutenberg error

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#661]
When selecting multiple text blocks and dragging them into a Tab container block or a Group block, an error is thrown in Gutenberg.  [See vid](https://drive.google.com/file/d/1DjVs0AO5GA5JWLfxa35T3yV4T31ASjtg/view?usp=sharing).  Likely this is a core Gutenberg error that we can't do anything about.  Luckily cutting and pasting will work as a workaround so a fix isn't urgent but maybe you can check it out at some point?  This is also a problem on LFPH and probably CNCF...

**Comment by thetwopct** [comment]
Linked issue: https://github.com/WordPress/gutenberg/issues/33610 

> This issue is not just with the Columns block. It affects all nested blocks eg. Group Block, Cover Block and any other 3rd party nestable block

This issue is not currently earmarked for fix in 5.8.1, so expect 5.8.2 (approx October) or 5.9 (December)
