### ISSUE TITLE
Post Meta Controls cacheing issue

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#662]
Figure out why meta values are being cached and the admin has to do a hard-refresh in order to see the latest values.

**Comment by cjyabraham** [comment]
I setup a vanilla WP site with just the MU plugin to setup the post meta control sidebars.  [Here is a recording of that](https://drive.google.com/file/d/1FBQQd7so8hejRVZ9VTB9ZaZiVg5G8Enn/view?usp=sharing).  So there is no problem.  This suggests the issue is not in the PCM plugin.

**Comment by cjyabraham** [comment]
I setup a vanilla Pantheon site with just the same MU plugin and the PMC plugin.  [Here is a recording of that](https://drive.google.com/file/d/1N9Cu1ChXH4TNKgjO5-_t242jvbwsKC98/view?usp=sharing).  So there is immediately a problem due to some cacheing on the Pantheon platform.

**Comment by cjyabraham** [comment]
Added [API cache-busting code](https://pantheon.io/docs/mu-plugin#wp-rest-api-wp-json-endpoints-cache) into the MU plugin and still the API call is getting cached.  [Here is a recording](https://drive.google.com/file/d/1xV7_qUr2FrlVFMZt7X3xavLFZvuSQTJY/view?usp=sharing).

**Comment by thetwopct** [comment]
I dont see the cache busting code in the MU plugin. I see it only in the themes functions.php file? 

> For actions or filters you want to run even when a theme's functions.php **isn't invoked by a request**, or before plugins are loaded by WordPress, you can create a Must-Use (MU) Plugin.

I don't think functions.php is invoked for API. 

Couple more thoughts  
1. We could try to no-cache a more general route. I.e all of json
2. I wonder if this should be applied with is_admin() check?

**Comment by cjyabraham** [comment]
For the tests above, I did have the cache-busting code in the MU plugin.  I stated so [above](https://github.com/LF-Engineering/lfevents/issues/662#issuecomment-894693781) and also showed it in [the vid](https://drive.google.com/file/d/1xV7_qUr2FrlVFMZt7X3xavLFZvuSQTJY/view?usp=sharing).  I also tried putting the code in wp-config.php.  Both places didn't work.

I did actually try to no-cache just '#^/wp-json/?#' (you'll see that in the vid too).  It didn't work.

**Comment by cjyabraham** [comment]
This is deployed across all sites and fixes the problem.
