### ISSUE TITLE
Live Stream Gutenberg block

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#663]
Create a Gutenberg block for gating livestream videos. The block would show a "Login to your LFID" button for people who aren't logged in and would show the video for those who are.  Since we don't know exactly what format we'll get the livestream video in, maybe just make the block a container with a code block inside which the admin could copy/paste embed codes/scripts.  Here's [an example of a live stream script](https://drive.google.com/file/d/1w0M1y_gZut_wWu5Hd36bBa29shtjY5PY/view?usp=sharing).

To implement the login part you can inspect the "Log in to download white paper" on [this page](https://www.linuxfoundation.org/resources/publications/software-defined-vertical-industries-transformation-through-open-source/).  You'll need to include [these scripts](https://github.com/LF-Engineering/lfevents/blob/main/web/wp-content/themes/lfevents/library/enqueue-scripts.php#L73-L78) for the show/hide via css to work but, of course, we should only include them on pages where this block is present.

Note that the video will be discoverable without logging in by someone who inspects the source of the page.  I think we can live with that.

**Comment by cjyabraham** [comment]
Example vid:
`<iframe src="https://video.ibm.com/combined-embed/24041981?videos=0&autoplay=true" style="border: 0;" webkitallowfullscreenallowfullscreen frameborder="no" width="1040" height="405"referrerpolicy="no-referrer-when-downgrade"></iframe>`

**Comment by cjyabraham** [comment]
I've deployed it to dev and it appears that the SSO login works from here.  When I get returned to the events page, however, I still don't see the embed.

[Here's my test page](https://dev-lfeventsci.pantheonsite.io/open-mainframe-summit/).

**Comment by thetwopct** [comment]
Not surprised. I wasn’t able to test it without dev SSO access. I’ll keep looking at it, but if you can find the old dev SSO details please do so.

**Comment by cjyabraham** [comment]
For some reason from [the Pantheon dev instance](http://dev-lfeventsci.pantheonsite.io/) it automatically uses the dev SSO instance.

**Comment by cjyabraham** [comment]
deployed
