### ISSUE TITLE
Cover block rounded corners style doesn't work

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#666]
The cover block at the bottom of [this page](https://events.linuxfoundation.org/agl-at-ces/) has the "Rounded Border" style set, however, the border doesn't show as rounded on the front or back-end:

<img width="1348" alt="Screen Shot 2021-08-30 at 2 08 26 PM" src="https://user-images.githubusercontent.com/463160/131384658-520a9211-4aa4-4b98-b1df-1aa14c6fa74c.png">

**Comment by thetwopct** [comment]
An issue with the image inside the cover, needed to apply an `overflow:hidden`

![2021-08-31-224114](https://user-images.githubusercontent.com/10615884/131533997-99055a3f-d19e-4d30-8be9-9eeb3b817798.gif)

**Comment by cjyabraham** [comment]
Deployed
