### ISSUE TITLE
Add Team page to main site

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#670]
We want a Team page added to the main events site.  To accommodate this, we need a main "About" menu with a dropdown like this:

About
- About LF Events
- Events Team
- Contact Us

The "Events team" page can be modeled on [CNCF Staff](https://www.cncf.io/people/staff/), however, Angela doesn't want bios for each person.

Should we put Code of Conduct in that menu too?

**Comment by thetwopct** [comment]
@cjyabraham 
- I've updated the styling as per Megans request
- I've added Megans preferred default avatar to LF Options settings page for when team member does not have picture
- I added an admin column in the Staff CPT so its easy to see in the admin which users have a featured image or not

**Comment by cjyabraham** [comment]
This is done.
