### ISSUE TITLE
Fix menu arrow

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#672]
The tip of the menu arrow seems to be slightly chopped off.  See [Kubecon China](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/)
<img width="280" alt="Screen Shot 2021-11-29 at 10 42 29 AM" src="https://user-images.githubusercontent.com/463160/143805380-e1a66484-4912-451a-8e0b-d9254954da6e.png">
<img width="251" alt="Screen Shot 2021-11-29 at 10 42 36 AM" src="https://user-images.githubusercontent.com/463160/143805388-cf080b5f-7e19-40e9-8a8d-da679f59888f.png">

**Comment by thetwopct** [comment]
I cant seem to reproduce; locally, production, safari, chrome, firefox.
Can you let me know browser, screen size, exact URLs (checked Kubecon china, cant see it)

**Comment by thetwopct** [comment]
OK I found one using Chrome on https://events.linuxfoundation.org/open-source-summit-japan/

![2021-11-29-141014](https://user-images.githubusercontent.com/10615884/143823528-07f99e42-ca11-45e1-a51b-3db7f6b679ab.jpg)

Seems to happen 1000px - 1100px

**Comment by cjyabraham** [comment]
Ya, I can't reproduce in other browsers... may be a real edge-case but there might be an easy fix...

**Comment by thetwopct** [comment]
I _think_ its an issue with using REM units, I switched to PX and now the places where I could find problems don't have problems. Lets try and see if it comes up again once the fix is live.

**Comment by cjyabraham** [comment]
Looks fixed to me:
<img width="319" alt="Screen Shot 2021-11-29 at 2 32 03 PM" src="https://user-images.githubusercontent.com/463160/143826056-584e2081-2959-464f-a8a0-96826f8a261a.png">

**Comment by cjyabraham** [comment]
Deployed
