### ISSUE TITLE
WP 5.9 upgrade issues

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#675]
These are the issues I've found on [the PR instance](https://pr-676-lfeventsci.pantheonsite.io):
- [ ] [Button with Expiry blocks](https://pr-676-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=82220&action=edit) don't render in editor and throw a TypeError in the console
- [ ] [Image boxes](https://pr-676-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=84933&action=edit) appear to be "invalid" however "Attempt Block Recovery" seems to fix it; can we see if we can avoid the "invalid" notice to begin with?
- [ ] [Track grids](https://pr-676-lfeventsci.pantheonsite.io/wp/wp-admin/post.php?post=130383&action=edit) appear to be "invalid" however "Attempt Block Recovery" seems to fix it; can we see if we can avoid the "invalid" notice to begin with? 

Once these issues are fixed we will get Megan to test.

Updates for Megan:
- dragging of multiple blocks into a group works now
- it's possible to drag/drop re-order blocks using the "List view".  [See here in this vid for a demo.](https://youtu.be/XvEG9XWD4JI?t=76)
- The Conditional Blocks Pro popup has a formatting issue, however, it doesn't stop you from using it and will likely be fixed in a subsequent version of the plugin
- For some Image boxes and Track grids, you'll need to "Attempt block recovery"

**Comment by thetwopct** [comment]
I've updated the buttons block, and also ran some updates on the Image Boxes and Track Grid but could not directly solve the "Attempt Block Recovery" prompt.
