### ISSUE TITLE
Multiple Leaks via wp-config.php

### ISSUE THREAD

**Issue by spacedog** [LF-Engineering/lfevents#685]
define( 'AUTH_KEY', '^J/[...]' );
define( 'SECURE_AUTH_KEY', 'dT,[...]' );
define( 'LOGGED_IN_KEY', '{0E[...]' );
define( 'NONCE_KEY', '|M9[...]' );
define( 'AUTH_SALT', 'CA-[...]' );
define( 'SECURE_AUTH_SALT', 'pi-[...]' );
define( 'LOGGED_IN_SALT', 'e+6[...]' );
define( 'NONCE_SALT', 'r%[...]' );

**Comment by cjyabraham** [comment]
Those are arbitrary and not used in production. [The production values](https://github.com/LF-Engineering/lfevents/blob/main/web/wp-config.php#L178) are stored elsewhere.
