### ISSUE TITLE
QQ link on KCCNC EU 2023 is broken

### ISSUE THREAD

**Issue by thetwopct** [LF-Engineering/lfevents#719]
Reported on [Twitter](https://twitter.com/angeloxx/status/1601216521144975360) that the QQ link on [KCCNC EU 2023 ](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/)event page is broken. 

The page it is linking too does not exist - http://v.qq.com/vplus/dbc4895dfc0a6ec609ad9e42a10507e0/videos

On older event pages we use the link - http://v.qq.com/s/videoplus/508102034 - so perhaps it just needs to be updated?

**Comment by cjyabraham** [comment]
Thanks. I've updated the link to the one that works.
