### ISSUE TITLE
Make Icon List show icons the same color as the text

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#730]
[Example of where this would be useful](https://events.linuxfoundation.org/cassandra-summit/register/#whats-included)

[As discussed](https://cloud-native.slack.com/archives/DN60NTB7W/p1674012920184269), make the icons be the same color as the text in an icon list.

**Comment by thetwopct** [comment]
@cjyabraham I've implemented this and pushed it to dev. I tried using "currentColor" property so any text color would also apply to the pseudo element, but it didn't work properly. As each icon needs to be hardcoded with its own color I have only implemented white versions for this time around which fixes the immediate problem.
