### ISSUE TITLE
Turn off XML-RPC

### ISSUE THREAD

**Issue by thetwopct** [LF-Engineering/lfevents#749]
Just creating this issue to track findings around XML-RPC

From WP Scan:

[+] XML-RPC seems to be enabled: https://events.linuxfoundation.org/wp/xmlrpc.php
 | Found By: Direct Access (Aggressive Detection)
 | Confidence: 100%
 | References:
 |  - http://codex.wordpress.org/XML-RPC_Pingback_API
 |  - https://www.rapid7.com/db/modules/auxiliary/scanner/http/wordpress_ghost_scanner/
 |  - https://www.rapid7.com/db/modules/auxiliary/dos/http/wordpress_xmlrpc_dos/
 |  - https://www.rapid7.com/db/modules/auxiliary/scanner/http/wordpress_xmlrpc_login/
 |  - https://www.rapid7.com/db/modules/auxiliary/scanner/http/wordpress_pingback_access/

**Comment by thetwopct** [comment]
From this page - https://docs.pantheon.io/guides/wordpress-developer/xml-rpc-attacks
"Pantheon blocked requests to xmlrpc.php by default in the [WordPress 5.4.2 core release](https://docs.pantheon.io/changelog/2020/07#wordpress-542)."

I had a quick look around to harden/update my default wp_head commands we discussed and would suggest we include the following if we are copying across the head_cleanup from CNCF:

```
		// controls whether XML-RPC methods requiring authentication are enabled.
		add_filter( 'xmlrpc_enabled', '__return_false' );

		// Unregister the whole XML-RPC method space.
		add_filter( 'xmlrpc_methods', fn( $methods ) => array() );
		
		// deactivate x-pingback HTTP header.
		add_filter(
			'wp_headers',
			function( $headers ) {
				unset( $headers['X-Pingback'] );
				return $headers;
			}
		);
```

**Comment by cjyabraham** [comment]
We are not using the Pantheon WordPress upstream. I suspect that upstream has modified the WP core files directly to block it. 

We could try out [this plugin](https://wordpress.org/plugins/disable-xml-rpc-api/) and see if that satisfies wp-scan. If so, we could pull out the code we need from it or just keep it installed? Alternatively we could install [one of those big security plugins like ](https://wpcerber.com/) and get it configured to work for us.

**Comment by thetwopct** [comment]
Ah ok makes sense. We could just protect the path in our pantheon.yml file then? https://docs.pantheon.io/pantheon-yml#protected-web-paths-override

**Comment by cjyabraham** [comment]
Ah, right. Ya, here is [the standard pantheon.yml that comes with the upstream, and it has a line for xmlrpc](https://github.com/pantheon-systems/WordPress/blob/default/pantheon.upstream.yml).
