### ISSUE TITLE
Button with Expiry fails when there is a strange <meta> tag in the button label

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#772]
As per Slack, somehow this tag `<meta charset="utf-8">` got inserted into the label of a button with expiry to end up with this code:
```
<!-- wp:lf/buttons-with-expiry {"conditionalBlocks":{"conditions":[]},"align":"center"} -->
<div class="wp-block-lf-buttons-with-expiry aligncenter"><!-- wp:lf/button-with-expiry {"customBackgroundColor":"#205bab","willExpire":true,"expireAt":"2022-09-03T02:59:00","expireText":"test"} -->
<div class="wp-block-lf-button-with-expiry"><a class="wp-block-button__link has-background button-large" href="https://events.linuxfoundation.org/wp-content/uploads/2023/04/OpenSSF_Day_Sponsorship_Package.pdf" style="background-color:#205bab;border-radius:5px" target="_blank" rel="noopener"><meta charset="utf-8">explore OpenSSF Day North America<br>Sponsorship opportunities</a></div>
<!-- /wp:lf/button-with-expiry --></div>
<!-- /wp:lf/buttons-with-expiry -->
```

When it is present, the button doesn't use the expiry text when it has expired. Instead, it just continues to show the unexpired button and text. So somehow the presence of the `<meta>` tag is causing that expiry processing to fail.

**Comment by thetwopct** [comment]
So the line of text I am using to test is:

`<meta charset="utf-8">explore OpenSSF Day North America<br>Sponsorship opportunities`

When I try to paste this line in to Button with Expiry, it will not paste in to the button
On a fresh WP install on Buttons block, it will not paste in to the button

**Comment by cjyabraham** [comment]
Maybe it was UTF-8 text that gets translated into that meta tag when pasted? I dunno... maybe this was a real anomaly. Perhaps we close and reopen only if it happens again?

**Comment by thetwopct** [comment]
Closing unless it happens again
