### ISSUE TITLE
Wrong day showing with date on event page

### ISSUE THREAD

**Issue by piyush-garg** [LF-Engineering/lfevents#814]
On the website https://events.linuxfoundation.org/kubeday-india/

The day is shown as Tuesday, but actually it is Friday.

**Comment by cjyabraham** [comment]
Thanks for reporting. This has now been fixed on [the homepage](https://events.linuxfoundation.org/kubeday-india/) and [the Schedule at a Glance page](https://events.linuxfoundation.org/kubeday-india/program/schedule-at-a-glance/).
