### ISSUE TITLE
SVGs appear to have blocks that are broken

### ISSUE THREAD

**Issue by cjyabraham** [LF-Engineering/lfevents#833]
All SVGs appear to now be broken in the editor and need "Attempt Block Recovery"

See [this post](https://events.linuxfoundation.org/wp/wp-admin/post.php?post=191913&action=edit) or [this one](https://events.linuxfoundation.org/wp/wp-admin/post.php?post=183302&action=edit). 

It's likely there was some update to WordPress recently that has caused this. Perhaps, as a first step, we should upgrade Safe SVG, however, my patch will need to be re-added to prevent performance issues. [See here for more info](https://github.com/LF-Engineering/lfevents/issues/567).

**Comment by thetwopct** [comment]
I've spent a lot of time trying to fix the SVG issue over the last few days, and unfortunately there does not seem to be a an easy fix or a global "fix all". There was recently some updates to WordPress around how it handles images and how it retrieves image sizes. And it seems WordPress is struggling to cope with SVG images that previously had a dimension applied to them. WordPress does not natively support SVG images, so this is why such a major breaking change has been overlooked by them.

If editors "Attempt to recover block" the current dimensions on the SVG will be removed and reset to null. So it's advised to "Convert to HTML" on the block first to get the original dimensions that were set on it, then "Convert to Blocks", then update the dimensions in the sidebar.

Blocks keep working even if they are "broken" and offering recovery - the markup displayed to the user never changes. So there is no urgency to fix each block (other than the annoying message) unless you want to move it, edit it, etc.

To prevent this happening in future (and also to prevent the SVGs behaving badly when inside columns etc) it may be that we need to switch every SVG to a dedicated "SVG Block" which then separates its handling from other images inserted via the "Image Block". We will discuss this.
